# -*- coding: utf-8 -*-
"""Fuente unica de datos de la Pokedex para TamaPoke.

Cada entrada: (num, slug, nombre_pantalla, tipo, evoluciona_a, nivel)
- slug: nombre en minusculas de la especie (identificador interno)
- nombre_pantalla: ASCII en mayusculas (la fuente GFX no tiene acentos)
- tipo: clave de TYPE_ACCENTS (color del nombre en la UI)
- evoluciona_a: numero de dex (0 = forma final); niveles gen 1 reales,
  piedras ~30 y por intercambio ~40 convertidos a nivel. Eevee (133) se
  ramifica en el codigo del juego (134/135/136 al azar).
"""

TYPE_ACCENTS = {
    'normal':    '#8a8a6a',
    'fuego':     '#e8503a',
    'agua':      '#4f93c4',
    'planta':    '#3c8a4c',
    'electrico': '#b8960b',
    'hielo':     '#4fb4c4',
    'lucha':     '#a5552d',
    'veneno':    '#8a4f9e',
    'tierra':    '#b08a3d',
    'psiquico':  '#d4527e',
    'bicho':     '#7a9a24',
    'roca':      '#93803d',
    'fantasma':  '#6a5a9e',
    'dragon':    '#5a52c4',
    'siniestro': '#5a4f73',
    'acero':     '#7f8c9a',
}

# Tipos de combate actuales para las especies incluidas.
# Fuente verificada: PokeAPI /pokemon/{id}. La UI sigue usando `tipo` como
# acento/bioma primario; estos pares se usan solo para el multiplicador battle.
BATTLE_TYPES = {
    1: ('grass', 'poison'), 2: ('grass', 'poison'), 3: ('grass', 'poison'),
    4: ('fire', None), 5: ('fire', None), 6: ('fire', 'flying'),
    7: ('water', None), 8: ('water', None), 9: ('water', None),
    10: ('bug', None), 11: ('bug', None), 12: ('bug', 'flying'),
    13: ('bug', 'poison'), 14: ('bug', 'poison'), 15: ('bug', 'poison'),
    16: ('normal', 'flying'), 17: ('normal', 'flying'), 18: ('normal', 'flying'),
    19: ('normal', None), 20: ('normal', None),
    21: ('normal', 'flying'), 22: ('normal', 'flying'),
    23: ('poison', None), 24: ('poison', None),
    25: ('electric', None), 26: ('electric', None),
    27: ('ground', None), 28: ('ground', None),
    29: ('poison', None), 30: ('poison', None), 31: ('poison', 'ground'),
    32: ('poison', None), 33: ('poison', None), 34: ('poison', 'ground'),
    35: ('fairy', None), 36: ('fairy', None),
    37: ('fire', None), 38: ('fire', None),
    39: ('normal', 'fairy'), 40: ('normal', 'fairy'),
    41: ('poison', 'flying'), 42: ('poison', 'flying'),
    43: ('grass', 'poison'), 44: ('grass', 'poison'), 45: ('grass', 'poison'),
    46: ('bug', 'grass'), 47: ('bug', 'grass'),
    48: ('bug', 'poison'), 49: ('bug', 'poison'),
    50: ('ground', None), 51: ('ground', None),
    52: ('normal', None), 53: ('normal', None),
    54: ('water', None), 55: ('water', None),
    56: ('fighting', None), 57: ('fighting', None),
    58: ('fire', None), 59: ('fire', None),
    60: ('water', None), 61: ('water', None), 62: ('water', 'fighting'),
    63: ('psychic', None), 64: ('psychic', None), 65: ('psychic', None),
    66: ('fighting', None), 67: ('fighting', None), 68: ('fighting', None),
    69: ('grass', 'poison'), 70: ('grass', 'poison'), 71: ('grass', 'poison'),
    72: ('water', 'poison'), 73: ('water', 'poison'),
    74: ('rock', 'ground'), 75: ('rock', 'ground'), 76: ('rock', 'ground'),
    77: ('fire', None), 78: ('fire', None),
    79: ('water', 'psychic'), 80: ('water', 'psychic'),
    81: ('electric', 'steel'), 82: ('electric', 'steel'),
    83: ('normal', 'flying'),
    84: ('normal', 'flying'), 85: ('normal', 'flying'),
    86: ('water', None), 87: ('water', 'ice'),
    88: ('poison', None), 89: ('poison', None),
    90: ('water', None), 91: ('water', 'ice'),
    92: ('ghost', 'poison'), 93: ('ghost', 'poison'), 94: ('ghost', 'poison'),
    95: ('rock', 'ground'),
    96: ('psychic', None), 97: ('psychic', None),
    98: ('water', None), 99: ('water', None),
    100: ('electric', None), 101: ('electric', None),
    102: ('grass', 'psychic'), 103: ('grass', 'psychic'),
    104: ('ground', None), 105: ('ground', None),
    106: ('fighting', None), 107: ('fighting', None),
    108: ('normal', None),
    109: ('poison', None), 110: ('poison', None),
    111: ('ground', 'rock'), 112: ('ground', 'rock'),
    113: ('normal', None),
    114: ('grass', None),
    115: ('normal', None),
    116: ('water', None), 117: ('water', None),
    118: ('water', None), 119: ('water', None),
    120: ('water', None), 121: ('water', 'psychic'),
    122: ('psychic', 'fairy'),
    123: ('bug', 'flying'),
    124: ('ice', 'psychic'),
    125: ('electric', None),
    126: ('fire', None),
    127: ('bug', None),
    128: ('normal', None),
    129: ('water', None), 130: ('water', 'flying'),
    131: ('water', 'ice'),
    132: ('normal', None),
    133: ('normal', None),
    134: ('water', None), 135: ('electric', None), 136: ('fire', None),
    137: ('normal', None),
    138: ('rock', 'water'), 139: ('rock', 'water'),
    140: ('rock', 'water'), 141: ('rock', 'water'),
    142: ('rock', 'flying'),
    143: ('normal', None),
    144: ('ice', 'flying'), 145: ('electric', 'flying'), 146: ('fire', 'flying'),
    147: ('dragon', None), 148: ('dragon', None), 149: ('dragon', 'flying'),
    150: ('psychic', None), 151: ('psychic', None),
    152: ('grass', None), 153: ('grass', None), 154: ('grass', None),
    155: ('fire', None), 156: ('fire', None), 157: ('fire', None),
    158: ('water', None), 159: ('water', None), 160: ('water', None),
    161: ('normal', None), 162: ('normal', None),
    163: ('normal', 'flying'), 164: ('normal', 'flying'),
    165: ('bug', 'flying'), 166: ('bug', 'flying'),
    167: ('bug', 'poison'), 168: ('bug', 'poison'),
    169: ('poison', 'flying'),
    170: ('water', 'electric'), 171: ('water', 'electric'),
    172: ('electric', None), 173: ('fairy', None),
    174: ('normal', 'fairy'), 175: ('fairy', None),
    176: ('fairy', 'flying'), 177: ('psychic', 'flying'),
    178: ('psychic', 'flying'), 179: ('electric', None),
    180: ('electric', None), 181: ('electric', None),
    182: ('grass', None), 183: ('water', 'fairy'),
    184: ('water', 'fairy'), 185: ('rock', None),
    186: ('water', None), 187: ('grass', 'flying'),
    188: ('grass', 'flying'), 189: ('grass', 'flying'),
    190: ('normal', None), 191: ('grass', None),
    192: ('grass', None), 193: ('bug', 'flying'),
    194: ('water', 'ground'), 195: ('water', 'ground'),
    196: ('psychic', None), 197: ('dark', None),
    198: ('dark', 'flying'), 199: ('water', 'psychic'),
    200: ('ghost', None), 201: ('psychic', None),
    202: ('psychic', None), 203: ('normal', 'psychic'),
    204: ('bug', None), 205: ('bug', 'steel'),
    206: ('normal', None), 207: ('ground', 'flying'),
    208: ('steel', 'ground'), 209: ('fairy', None),
    210: ('fairy', None), 211: ('water', 'poison'),
    212: ('bug', 'steel'), 213: ('bug', 'rock'),
    214: ('bug', 'fighting'), 215: ('dark', 'ice'),
    216: ('normal', None), 217: ('normal', None),
    218: ('fire', None), 219: ('fire', 'rock'),
    220: ('ice', 'ground'), 221: ('ice', 'ground'),
    222: ('water', 'rock'), 223: ('water', None),
    224: ('water', None), 225: ('ice', 'flying'),
    226: ('water', 'flying'), 227: ('steel', 'flying'),
    228: ('dark', 'fire'), 229: ('dark', 'fire'),
    230: ('water', 'dragon'), 231: ('ground', None),
    232: ('ground', None), 233: ('normal', None),
    234: ('normal', None), 235: ('normal', None),
    236: ('fighting', None), 237: ('fighting', None),
    238: ('ice', 'psychic'), 239: ('electric', None),
    240: ('fire', None), 241: ('normal', None),
    242: ('normal', None), 243: ('electric', None),
    244: ('fire', None), 245: ('water', None),
    246: ('rock', 'ground'), 247: ('rock', 'ground'),
    248: ('rock', 'dark'), 249: ('psychic', 'flying'),
    250: ('fire', 'flying'), 251: ('psychic', 'grass'),
    252: ('grass', None),
    253: ('grass', None),
    254: ('grass', None),
    255: ('fire', None),
    256: ('fire', 'fighting'),
    257: ('fire', 'fighting'),
    258: ('water', None),
    259: ('water', 'ground'),
    260: ('water', 'ground'),
    261: ('dark', None),
    262: ('dark', None),
    263: ('normal', None),
    264: ('normal', None),
    265: ('bug', None),
    266: ('bug', None),
    267: ('bug', 'flying'),
    268: ('bug', None),
    269: ('bug', 'poison'),
    270: ('water', 'grass'),
    271: ('water', 'grass'),
    272: ('water', 'grass'),
    273: ('grass', None),
    274: ('grass', 'dark'),
    275: ('grass', 'dark'),
    276: ('normal', 'flying'),
    277: ('normal', 'flying'),
    278: ('water', 'flying'),
    279: ('water', 'flying'),
    280: ('psychic', 'fairy'),
    281: ('psychic', 'fairy'),
    282: ('psychic', 'fairy'),
    283: ('bug', 'water'),
    284: ('bug', 'flying'),
    285: ('grass', None),
    286: ('grass', 'fighting'),
    287: ('normal', None),
    288: ('normal', None),
    289: ('normal', None),
    290: ('bug', 'ground'),
    291: ('bug', 'flying'),
    292: ('bug', 'ghost'),
    293: ('normal', None),
    294: ('normal', None),
    295: ('normal', None),
    296: ('fighting', None),
    297: ('fighting', None),
    298: ('normal', 'fairy'),
    299: ('rock', None),
    300: ('normal', None),
    301: ('normal', None),
    302: ('dark', 'ghost'),
    303: ('steel', 'fairy'),
    304: ('steel', 'rock'),
    305: ('steel', 'rock'),
    306: ('steel', 'rock'),
    307: ('fighting', 'psychic'),
    308: ('fighting', 'psychic'),
    309: ('electric', None),
    310: ('electric', None),
    311: ('electric', None),
    312: ('electric', None),
    313: ('bug', None),
    314: ('bug', None),
    315: ('grass', 'poison'),
    316: ('poison', None),
    317: ('poison', None),
    318: ('water', 'dark'),
    319: ('water', 'dark'),
    320: ('water', None),
    321: ('water', None),
    322: ('fire', 'ground'),
    323: ('fire', 'ground'),
    324: ('fire', None),
    325: ('psychic', None),
    326: ('psychic', None),
    327: ('normal', None),
    328: ('ground', None),
    329: ('ground', 'dragon'),
    330: ('ground', 'dragon'),
    331: ('grass', None),
    332: ('grass', 'dark'),
    333: ('normal', 'flying'),
    334: ('dragon', 'flying'),
    335: ('normal', None),
    336: ('poison', None),
    337: ('rock', 'psychic'),
    338: ('rock', 'psychic'),
    339: ('water', 'ground'),
    340: ('water', 'ground'),
    341: ('water', None),
    342: ('water', 'dark'),
    343: ('ground', 'psychic'),
    344: ('ground', 'psychic'),
    345: ('rock', 'grass'),
    346: ('rock', 'grass'),
    347: ('rock', 'bug'),
    348: ('rock', 'bug'),
    349: ('water', None),
    350: ('water', None),
    351: ('normal', None),
    352: ('normal', None),
    353: ('ghost', None),
    354: ('ghost', None),
    355: ('ghost', None),
    356: ('ghost', None),
    357: ('grass', 'flying'),
    358: ('psychic', None),
    359: ('dark', None),
    360: ('psychic', None),
    361: ('ice', None),
    362: ('ice', None),
    363: ('ice', 'water'),
    364: ('ice', 'water'),
    365: ('ice', 'water'),
    366: ('water', None),
    367: ('water', None),
    368: ('water', None),
    369: ('water', 'rock'),
    370: ('water', None),
    371: ('dragon', None),
    372: ('dragon', None),
    373: ('dragon', 'flying'),
    374: ('steel', 'psychic'),
    375: ('steel', 'psychic'),
    376: ('steel', 'psychic'),
    377: ('rock', None),
    378: ('ice', None),
    379: ('steel', None),
    380: ('dragon', 'psychic'),
    381: ('dragon', 'psychic'),
    382: ('water', None),
    383: ('ground', None),
    384: ('dragon', 'flying'),
    385: ('steel', 'psychic'),
    386: ('psychic', None),
}

# Nombres localizados para la UI en el orden de Lang: ES, EN, FR, DE, IT, PT.
# Fuente: PokeAPI pokemon-species/{id}; PT usa los nombres internacionales EN.
# Normalizados a ASCII/mayusculas porque la fuente del firmware no tiene acentos.
LOCALIZED_NAMES = {
    1: ('BULBASAUR', 'BULBASAUR', 'BULBIZARRE', 'BISASAM', 'BULBASAUR', 'BULBASAUR'),
    2: ('IVYSAUR', 'IVYSAUR', 'HERBIZARRE', 'BISAKNOSP', 'IVYSAUR', 'IVYSAUR'),
    3: ('VENUSAUR', 'VENUSAUR', 'FLORIZARRE', 'BISAFLOR', 'VENUSAUR', 'VENUSAUR'),
    4: ('CHARMANDER', 'CHARMANDER', 'SALAMECHE', 'GLUMANDA', 'CHARMANDER', 'CHARMANDER'),
    5: ('CHARMELEON', 'CHARMELEON', 'REPTINCEL', 'GLUTEXO', 'CHARMELEON', 'CHARMELEON'),
    6: ('CHARIZARD', 'CHARIZARD', 'DRACAUFEU', 'GLURAK', 'CHARIZARD', 'CHARIZARD'),
    7: ('SQUIRTLE', 'SQUIRTLE', 'CARAPUCE', 'SCHIGGY', 'SQUIRTLE', 'SQUIRTLE'),
    8: ('WARTORTLE', 'WARTORTLE', 'CARABAFFE', 'SCHILLOK', 'WARTORTLE', 'WARTORTLE'),
    9: ('BLASTOISE', 'BLASTOISE', 'TORTANK', 'TURTOK', 'BLASTOISE', 'BLASTOISE'),
    10: ('CATERPIE', 'CATERPIE', 'CHENIPAN', 'RAUPY', 'CATERPIE', 'CATERPIE'),
    11: ('METAPOD', 'METAPOD', 'CHRYSACIER', 'SAFCON', 'METAPOD', 'METAPOD'),
    12: ('BUTTERFREE', 'BUTTERFREE', 'PAPILUSION', 'SMETTBO', 'BUTTERFREE', 'BUTTERFREE'),
    13: ('WEEDLE', 'WEEDLE', 'ASPICOT', 'HORNLIU', 'WEEDLE', 'WEEDLE'),
    14: ('KAKUNA', 'KAKUNA', 'COCONFORT', 'KOKUNA', 'KAKUNA', 'KAKUNA'),
    15: ('BEEDRILL', 'BEEDRILL', 'DARDARGNAN', 'BIBOR', 'BEEDRILL', 'BEEDRILL'),
    16: ('PIDGEY', 'PIDGEY', 'ROUCOOL', 'TAUBSI', 'PIDGEY', 'PIDGEY'),
    17: ('PIDGEOTTO', 'PIDGEOTTO', 'ROUCOUPS', 'TAUBOGA', 'PIDGEOTTO', 'PIDGEOTTO'),
    18: ('PIDGEOT', 'PIDGEOT', 'ROUCARNAGE', 'TAUBOSS', 'PIDGEOT', 'PIDGEOT'),
    19: ('RATTATA', 'RATTATA', 'RATTATA', 'RATTFRATZ', 'RATTATA', 'RATTATA'),
    20: ('RATICATE', 'RATICATE', 'RATTATAC', 'RATTIKARL', 'RATICATE', 'RATICATE'),
    21: ('SPEAROW', 'SPEAROW', 'PIAFABEC', 'HABITAK', 'SPEAROW', 'SPEAROW'),
    22: ('FEAROW', 'FEAROW', 'RAPASDEPIC', 'IBITAK', 'FEAROW', 'FEAROW'),
    23: ('EKANS', 'EKANS', 'ABO', 'RETTAN', 'EKANS', 'EKANS'),
    24: ('ARBOK', 'ARBOK', 'ARBOK', 'ARBOK', 'ARBOK', 'ARBOK'),
    25: ('PIKACHU', 'PIKACHU', 'PIKACHU', 'PIKACHU', 'PIKACHU', 'PIKACHU'),
    26: ('RAICHU', 'RAICHU', 'RAICHU', 'RAICHU', 'RAICHU', 'RAICHU'),
    27: ('SANDSHREW', 'SANDSHREW', 'SABELETTE', 'SANDAN', 'SANDSHREW', 'SANDSHREW'),
    28: ('SANDSLASH', 'SANDSLASH', 'SABLAIREAU', 'SANDAMER', 'SANDSLASH', 'SANDSLASH'),
    29: ('NIDORAN F', 'NIDORAN F', 'NIDORAN F', 'NIDORAN F', 'NIDORAN F', 'NIDORAN F'),
    30: ('NIDORINA', 'NIDORINA', 'NIDORINA', 'NIDORINA', 'NIDORINA', 'NIDORINA'),
    31: ('NIDOQUEEN', 'NIDOQUEEN', 'NIDOQUEEN', 'NIDOQUEEN', 'NIDOQUEEN', 'NIDOQUEEN'),
    32: ('NIDORAN M', 'NIDORAN M', 'NIDORAN M', 'NIDORAN M', 'NIDORAN M', 'NIDORAN M'),
    33: ('NIDORINO', 'NIDORINO', 'NIDORINO', 'NIDORINO', 'NIDORINO', 'NIDORINO'),
    34: ('NIDOKING', 'NIDOKING', 'NIDOKING', 'NIDOKING', 'NIDOKING', 'NIDOKING'),
    35: ('CLEFAIRY', 'CLEFAIRY', 'MELOFEE', 'PIEPI', 'CLEFAIRY', 'CLEFAIRY'),
    36: ('CLEFABLE', 'CLEFABLE', 'MELODELFE', 'PIXI', 'CLEFABLE', 'CLEFABLE'),
    37: ('VULPIX', 'VULPIX', 'GOUPIX', 'VULPIX', 'VULPIX', 'VULPIX'),
    38: ('NINETALES', 'NINETALES', 'FEUNARD', 'VULNONA', 'NINETALES', 'NINETALES'),
    39: ('JIGGLYPUFF', 'JIGGLYPUFF', 'RONDOUDOU', 'PUMMELUFF', 'JIGGLYPUFF', 'JIGGLYPUFF'),
    40: ('WIGGLYTUFF', 'WIGGLYTUFF', 'GRODOUDOU', 'KNUDDELUFF', 'WIGGLYTUFF', 'WIGGLYTUFF'),
    41: ('ZUBAT', 'ZUBAT', 'NOSFERAPTI', 'ZUBAT', 'ZUBAT', 'ZUBAT'),
    42: ('GOLBAT', 'GOLBAT', 'NOSFERALTO', 'GOLBAT', 'GOLBAT', 'GOLBAT'),
    43: ('ODDISH', 'ODDISH', 'MYSTHERBE', 'MYRAPLA', 'ODDISH', 'ODDISH'),
    44: ('GLOOM', 'GLOOM', 'ORTIDE', 'DUFLOR', 'GLOOM', 'GLOOM'),
    45: ('VILEPLUME', 'VILEPLUME', 'RAFFLESIA', 'GIFLOR', 'VILEPLUME', 'VILEPLUME'),
    46: ('PARAS', 'PARAS', 'PARAS', 'PARAS', 'PARAS', 'PARAS'),
    47: ('PARASECT', 'PARASECT', 'PARASECT', 'PARASEK', 'PARASECT', 'PARASECT'),
    48: ('VENONAT', 'VENONAT', 'MIMITOSS', 'BLUZUK', 'VENONAT', 'VENONAT'),
    49: ('VENOMOTH', 'VENOMOTH', 'AEROMITE', 'OMOT', 'VENOMOTH', 'VENOMOTH'),
    50: ('DIGLETT', 'DIGLETT', 'TAUPIQUEUR', 'DIGDA', 'DIGLETT', 'DIGLETT'),
    51: ('DUGTRIO', 'DUGTRIO', 'TRIOPIKEUR', 'DIGDRI', 'DUGTRIO', 'DUGTRIO'),
    52: ('MEOWTH', 'MEOWTH', 'MIAOUSS', 'MAUZI', 'MEOWTH', 'MEOWTH'),
    53: ('PERSIAN', 'PERSIAN', 'PERSIAN', 'SNOBILIKAT', 'PERSIAN', 'PERSIAN'),
    54: ('PSYDUCK', 'PSYDUCK', 'PSYKOKWAK', 'ENTON', 'PSYDUCK', 'PSYDUCK'),
    55: ('GOLDUCK', 'GOLDUCK', 'AKWAKWAK', 'ENTORON', 'GOLDUCK', 'GOLDUCK'),
    56: ('MANKEY', 'MANKEY', 'FEROSINGE', 'MENKI', 'MANKEY', 'MANKEY'),
    57: ('PRIMEAPE', 'PRIMEAPE', 'COLOSSINGE', 'RASAFF', 'PRIMEAPE', 'PRIMEAPE'),
    58: ('GROWLITHE', 'GROWLITHE', 'CANINOS', 'FUKANO', 'GROWLITHE', 'GROWLITHE'),
    59: ('ARCANINE', 'ARCANINE', 'ARCANIN', 'ARKANI', 'ARCANINE', 'ARCANINE'),
    60: ('POLIWAG', 'POLIWAG', 'PTITARD', 'QUAPSEL', 'POLIWAG', 'POLIWAG'),
    61: ('POLIWHIRL', 'POLIWHIRL', 'TETARTE', 'QUAPUTZI', 'POLIWHIRL', 'POLIWHIRL'),
    62: ('POLIWRATH', 'POLIWRATH', 'TARTARD', 'QUAPPO', 'POLIWRATH', 'POLIWRATH'),
    63: ('ABRA', 'ABRA', 'ABRA', 'ABRA', 'ABRA', 'ABRA'),
    64: ('KADABRA', 'KADABRA', 'KADABRA', 'KADABRA', 'KADABRA', 'KADABRA'),
    65: ('ALAKAZAM', 'ALAKAZAM', 'ALAKAZAM', 'SIMSALA', 'ALAKAZAM', 'ALAKAZAM'),
    66: ('MACHOP', 'MACHOP', 'MACHOC', 'MACHOLLO', 'MACHOP', 'MACHOP'),
    67: ('MACHOKE', 'MACHOKE', 'MACHOPEUR', 'MASCHOCK', 'MACHOKE', 'MACHOKE'),
    68: ('MACHAMP', 'MACHAMP', 'MACKOGNEUR', 'MACHOMEI', 'MACHAMP', 'MACHAMP'),
    69: ('BELLSPROUT', 'BELLSPROUT', 'CHETIFLOR', 'KNOFENSA', 'BELLSPROUT', 'BELLSPROUT'),
    70: ('WEEPINBELL', 'WEEPINBELL', 'BOUSTIFLOR', 'ULTRIGARIA', 'WEEPINBELL', 'WEEPINBELL'),
    71: ('VICTREEBEL', 'VICTREEBEL', 'EMPIFLOR', 'SARZENIA', 'VICTREEBEL', 'VICTREEBEL'),
    72: ('TENTACOOL', 'TENTACOOL', 'TENTACOOL', 'TENTACHA', 'TENTACOOL', 'TENTACOOL'),
    73: ('TENTACRUEL', 'TENTACRUEL', 'TENTACRUEL', 'TENTOXA', 'TENTACRUEL', 'TENTACRUEL'),
    74: ('GEODUDE', 'GEODUDE', 'RACAILLOU', 'KLEINSTEIN', 'GEODUDE', 'GEODUDE'),
    75: ('GRAVELER', 'GRAVELER', 'GRAVALANCH', 'GEOROK', 'GRAVELER', 'GRAVELER'),
    76: ('GOLEM', 'GOLEM', 'GROLEM', 'GEOWAZ', 'GOLEM', 'GOLEM'),
    77: ('PONYTA', 'PONYTA', 'PONYTA', 'PONITA', 'PONYTA', 'PONYTA'),
    78: ('RAPIDASH', 'RAPIDASH', 'GALOPA', 'GALLOPA', 'RAPIDASH', 'RAPIDASH'),
    79: ('SLOWPOKE', 'SLOWPOKE', 'RAMOLOSS', 'FLEGMON', 'SLOWPOKE', 'SLOWPOKE'),
    80: ('SLOWBRO', 'SLOWBRO', 'FLAGADOSS', 'LAHMUS', 'SLOWBRO', 'SLOWBRO'),
    81: ('MAGNEMITE', 'MAGNEMITE', 'MAGNETI', 'MAGNETILO', 'MAGNEMITE', 'MAGNEMITE'),
    82: ('MAGNETON', 'MAGNETON', 'MAGNETON', 'MAGNETON', 'MAGNETON', 'MAGNETON'),
    83: ('FARFETCHD', 'FARFETCHD', 'CANARTICHO', 'PORENTA', 'FARFETCHD', 'FARFETCHD'),
    84: ('DODUO', 'DODUO', 'DODUO', 'DODU', 'DODUO', 'DODUO'),
    85: ('DODRIO', 'DODRIO', 'DODRIO', 'DODRI', 'DODRIO', 'DODRIO'),
    86: ('SEEL', 'SEEL', 'OTARIA', 'JUROB', 'SEEL', 'SEEL'),
    87: ('DEWGONG', 'DEWGONG', 'LAMANTINE', 'JUGONG', 'DEWGONG', 'DEWGONG'),
    88: ('GRIMER', 'GRIMER', 'TADMORV', 'SLEIMA', 'GRIMER', 'GRIMER'),
    89: ('MUK', 'MUK', 'GROTADMORV', 'SLEIMOK', 'MUK', 'MUK'),
    90: ('SHELLDER', 'SHELLDER', 'KOKIYAS', 'MUSCHAS', 'SHELLDER', 'SHELLDER'),
    91: ('CLOYSTER', 'CLOYSTER', 'CRUSTABRI', 'AUSTOS', 'CLOYSTER', 'CLOYSTER'),
    92: ('GASTLY', 'GASTLY', 'FANTOMINUS', 'NEBULAK', 'GASTLY', 'GASTLY'),
    93: ('HAUNTER', 'HAUNTER', 'SPECTRUM', 'ALPOLLO', 'HAUNTER', 'HAUNTER'),
    94: ('GENGAR', 'GENGAR', 'ECTOPLASMA', 'GENGAR', 'GENGAR', 'GENGAR'),
    95: ('ONIX', 'ONIX', 'ONIX', 'ONIX', 'ONIX', 'ONIX'),
    96: ('DROWZEE', 'DROWZEE', 'SOPORIFIK', 'TRAUMATO', 'DROWZEE', 'DROWZEE'),
    97: ('HYPNO', 'HYPNO', 'HYPNOMADE', 'HYPNO', 'HYPNO', 'HYPNO'),
    98: ('KRABBY', 'KRABBY', 'KRABBY', 'KRABBY', 'KRABBY', 'KRABBY'),
    99: ('KINGLER', 'KINGLER', 'KRABBOSS', 'KINGLER', 'KINGLER', 'KINGLER'),
    100: ('VOLTORB', 'VOLTORB', 'VOLTORBE', 'VOLTOBAL', 'VOLTORB', 'VOLTORB'),
    101: ('ELECTRODE', 'ELECTRODE', 'ELECTRODE', 'LEKTROBAL', 'ELECTRODE', 'ELECTRODE'),
    102: ('EXEGGCUTE', 'EXEGGCUTE', 'NOEUNOEUF', 'OWEI', 'EXEGGCUTE', 'EXEGGCUTE'),
    103: ('EXEGGUTOR', 'EXEGGUTOR', 'NOADKOKO', 'KOKOWEI', 'EXEGGUTOR', 'EXEGGUTOR'),
    104: ('CUBONE', 'CUBONE', 'OSSELAIT', 'TRAGOSSO', 'CUBONE', 'CUBONE'),
    105: ('MAROWAK', 'MAROWAK', 'OSSATUEUR', 'KNOGGA', 'MAROWAK', 'MAROWAK'),
    106: ('HITMONLEE', 'HITMONLEE', 'KICKLEE', 'KICKLEE', 'HITMONLEE', 'HITMONLEE'),
    107: ('HITMONCHAN', 'HITMONCHAN', 'TYGNON', 'NOCKCHAN', 'HITMONCHAN', 'HITMONCHAN'),
    108: ('LICKITUNG', 'LICKITUNG', 'EXCELANGUE', 'SCHLURP', 'LICKITUNG', 'LICKITUNG'),
    109: ('KOFFING', 'KOFFING', 'SMOGO', 'SMOGON', 'KOFFING', 'KOFFING'),
    110: ('WEEZING', 'WEEZING', 'SMOGOGO', 'SMOGMOG', 'WEEZING', 'WEEZING'),
    111: ('RHYHORN', 'RHYHORN', 'RHINOCORNE', 'RIHORN', 'RHYHORN', 'RHYHORN'),
    112: ('RHYDON', 'RHYDON', 'RHINOFEROS', 'RIZEROS', 'RHYDON', 'RHYDON'),
    113: ('CHANSEY', 'CHANSEY', 'LEVEINARD', 'CHANEIRA', 'CHANSEY', 'CHANSEY'),
    114: ('TANGELA', 'TANGELA', 'SAQUEDENEU', 'TANGELA', 'TANGELA', 'TANGELA'),
    115: ('KANGASKHAN', 'KANGASKHAN', 'KANGOUREX', 'KANGAMA', 'KANGASKHAN', 'KANGASKHAN'),
    116: ('HORSEA', 'HORSEA', 'HYPOTREMPE', 'SEEPER', 'HORSEA', 'HORSEA'),
    117: ('SEADRA', 'SEADRA', 'HYPOCEAN', 'SEEMON', 'SEADRA', 'SEADRA'),
    118: ('GOLDEEN', 'GOLDEEN', 'POISSIRENE', 'GOLDINI', 'GOLDEEN', 'GOLDEEN'),
    119: ('SEAKING', 'SEAKING', 'POISSOROY', 'GOLKING', 'SEAKING', 'SEAKING'),
    120: ('STARYU', 'STARYU', 'STARI', 'STERNDU', 'STARYU', 'STARYU'),
    121: ('STARMIE', 'STARMIE', 'STAROSS', 'STARMIE', 'STARMIE', 'STARMIE'),
    122: ('MR. MIME', 'MR. MIME', 'M. MIME', 'PANTIMOS', 'MR. MIME', 'MR. MIME'),
    123: ('SCYTHER', 'SCYTHER', 'INSECATEUR', 'SICHLOR', 'SCYTHER', 'SCYTHER'),
    124: ('JYNX', 'JYNX', 'LIPPOUTOU', 'ROSSANA', 'JYNX', 'JYNX'),
    125: ('ELECTABUZZ', 'ELECTABUZZ', 'ELEKTEK', 'ELEKTEK', 'ELECTABUZZ', 'ELECTABUZZ'),
    126: ('MAGMAR', 'MAGMAR', 'MAGMAR', 'MAGMAR', 'MAGMAR', 'MAGMAR'),
    127: ('PINSIR', 'PINSIR', 'SCARABRUTE', 'PINSIR', 'PINSIR', 'PINSIR'),
    128: ('TAUROS', 'TAUROS', 'TAUROS', 'TAUROS', 'TAUROS', 'TAUROS'),
    129: ('MAGIKARP', 'MAGIKARP', 'MAGICARPE', 'KARPADOR', 'MAGIKARP', 'MAGIKARP'),
    130: ('GYARADOS', 'GYARADOS', 'LEVIATOR', 'GARADOS', 'GYARADOS', 'GYARADOS'),
    131: ('LAPRAS', 'LAPRAS', 'LOKHLASS', 'LAPRAS', 'LAPRAS', 'LAPRAS'),
    132: ('DITTO', 'DITTO', 'METAMORPH', 'DITTO', 'DITTO', 'DITTO'),
    133: ('EEVEE', 'EEVEE', 'EVOLI', 'EVOLI', 'EEVEE', 'EEVEE'),
    134: ('VAPOREON', 'VAPOREON', 'AQUALI', 'AQUANA', 'VAPOREON', 'VAPOREON'),
    135: ('JOLTEON', 'JOLTEON', 'VOLTALI', 'BLITZA', 'JOLTEON', 'JOLTEON'),
    136: ('FLAREON', 'FLAREON', 'PYROLI', 'FLAMARA', 'FLAREON', 'FLAREON'),
    137: ('PORYGON', 'PORYGON', 'PORYGON', 'PORYGON', 'PORYGON', 'PORYGON'),
    138: ('OMANYTE', 'OMANYTE', 'AMONITA', 'AMONITAS', 'OMANYTE', 'OMANYTE'),
    139: ('OMASTAR', 'OMASTAR', 'AMONISTAR', 'AMOROSO', 'OMASTAR', 'OMASTAR'),
    140: ('KABUTO', 'KABUTO', 'KABUTO', 'KABUTO', 'KABUTO', 'KABUTO'),
    141: ('KABUTOPS', 'KABUTOPS', 'KABUTOPS', 'KABUTOPS', 'KABUTOPS', 'KABUTOPS'),
    142: ('AERODACTYL', 'AERODACTYL', 'PTERA', 'AERODACTYL', 'AERODACTYL', 'AERODACTYL'),
    143: ('SNORLAX', 'SNORLAX', 'RONFLEX', 'RELAXO', 'SNORLAX', 'SNORLAX'),
    144: ('ARTICUNO', 'ARTICUNO', 'ARTIKODIN', 'ARKTOS', 'ARTICUNO', 'ARTICUNO'),
    145: ('ZAPDOS', 'ZAPDOS', 'ELECTHOR', 'ZAPDOS', 'ZAPDOS', 'ZAPDOS'),
    146: ('MOLTRES', 'MOLTRES', 'SULFURA', 'LAVADOS', 'MOLTRES', 'MOLTRES'),
    147: ('DRATINI', 'DRATINI', 'MINIDRACO', 'DRATINI', 'DRATINI', 'DRATINI'),
    148: ('DRAGONAIR', 'DRAGONAIR', 'DRACO', 'DRAGONIR', 'DRAGONAIR', 'DRAGONAIR'),
    149: ('DRAGONITE', 'DRAGONITE', 'DRACOLOSSE', 'DRAGORAN', 'DRAGONITE', 'DRAGONITE'),
    150: ('MEWTWO', 'MEWTWO', 'MEWTWO', 'MEWTU', 'MEWTWO', 'MEWTWO'),
    151: ('MEW', 'MEW', 'MEW', 'MEW', 'MEW', 'MEW'),
    152: ('CHIKORITA', 'CHIKORITA', 'GERMIGNON', 'ENDIVIE', 'CHIKORITA', 'CHIKORITA'),
    153: ('BAYLEEF', 'BAYLEEF', 'MACRONIUM', 'LORBLATT', 'BAYLEEF', 'BAYLEEF'),
    154: ('MEGANIUM', 'MEGANIUM', 'MEGANIUM', 'MEGANIE', 'MEGANIUM', 'MEGANIUM'),
    155: ('CYNDAQUIL', 'CYNDAQUIL', 'HERICENDRE', 'FEURIGEL', 'CYNDAQUIL', 'CYNDAQUIL'),
    156: ('QUILAVA', 'QUILAVA', 'FEURISSON', 'IGELAVAR', 'QUILAVA', 'QUILAVA'),
    157: ('TYPHLOSION', 'TYPHLOSION', 'TYPHLOSION', 'TORNUPTO', 'TYPHLOSION', 'TYPHLOSION'),
    158: ('TOTODILE', 'TOTODILE', 'KAIMINUS', 'KARNIMANI', 'TOTODILE', 'TOTODILE'),
    159: ('CROCONAW', 'CROCONAW', 'CROCRODIL', 'TYRACROC', 'CROCONAW', 'CROCONAW'),
    160: ('FERALIGATR', 'FERALIGATR', 'ALIGATUEUR', 'IMPERGATOR', 'FERALIGATR', 'FERALIGATR'),
    161: ('SENTRET', 'SENTRET', 'FOUINET', 'WIESOR', 'SENTRET', 'SENTRET'),
    162: ('FURRET', 'FURRET', 'FOUINAR', 'WIESENIOR', 'FURRET', 'FURRET'),
    163: ('HOOTHOOT', 'HOOTHOOT', 'HOOTHOOT', 'HOOTHOOT', 'HOOTHOOT', 'HOOTHOOT'),
    164: ('NOCTOWL', 'NOCTOWL', 'NOARFANG', 'NOCTUH', 'NOCTOWL', 'NOCTOWL'),
    165: ('LEDYBA', 'LEDYBA', 'COXY', 'LEDYBA', 'LEDYBA', 'LEDYBA'),
    166: ('LEDIAN', 'LEDIAN', 'COXICLAQUE', 'LEDIAN', 'LEDIAN', 'LEDIAN'),
    167: ('SPINARAK', 'SPINARAK', 'MIMIGAL', 'WEBARAK', 'SPINARAK', 'SPINARAK'),
    168: ('ARIADOS', 'ARIADOS', 'MIGALOS', 'ARIADOS', 'ARIADOS', 'ARIADOS'),
    169: ('CROBAT', 'CROBAT', 'NOSTENFER', 'KROBAT', 'CROBAT', 'CROBAT'),
    170: ('CHINCHOU', 'CHINCHOU', 'LOUPIO', 'LAMPI', 'CHINCHOU', 'CHINCHOU'),
    171: ('LANTURN', 'LANTURN', 'LANTURN', 'LANTURN', 'LANTURN', 'LANTURN'),
    172: ('PICHU', 'PICHU', 'PICHU', 'PICHU', 'PICHU', 'PICHU'),
    173: ('CLEFFA', 'CLEFFA', 'MELOFEE', 'PII', 'CLEFFA', 'CLEFFA'),
    174: ('IGGLYBUFF', 'IGGLYBUFF', 'TOUDOUDOU', 'PUMMELUFF', 'IGGLYBUFF', 'IGGLYBUFF'),
    175: ('TOGEPI', 'TOGEPI', 'TOGEPI', 'TOGEPI', 'TOGEPI', 'TOGEPI'),
    176: ('TOGETIC', 'TOGETIC', 'TOGETIC', 'TOGETIC', 'TOGETIC', 'TOGETIC'),
    177: ('NATU', 'NATU', 'NATU', 'NATU', 'NATU', 'NATU'),
    178: ('XATU', 'XATU', 'XATU', 'XATU', 'XATU', 'XATU'),
    179: ('MAREEP', 'MAREEP', 'WATTWAP', 'WATTZAPF', 'MAREEP', 'MAREEP'),
    180: ('FLAAFFY', 'FLAAFFY', 'LAINERGIE', 'WAATY', 'FLAAFFY', 'FLAAFFY'),
    181: ('AMPHAROS', 'AMPHAROS', 'PHARAMP', 'AMPHAROS', 'AMPHAROS', 'AMPHAROS'),
    182: ('BELLOSSOM', 'BELLOSSOM', 'JOLIFLOR', 'BLUBELLA', 'BELLOSSOM', 'BELLOSSOM'),
    183: ('MARILL', 'MARILL', 'MARILL', 'MARILL', 'MARILL', 'MARILL'),
    184: ('AZUMARILL', 'AZUMARILL', 'AZUMARILL', 'AZUMARILL', 'AZUMARILL', 'AZUMARILL'),
    185: ('SUDOWOODO', 'SUDOWOODO', 'SIMULARBRE', 'MOGELBAUM', 'SUDOWOODO', 'SUDOWOODO'),
    186: ('POLITOED', 'POLITOED', 'TARPAUD', 'QUAXO', 'POLITOED', 'POLITOED'),
    187: ('HOPPIP', 'HOPPIP', 'GRANIVOL', 'HOPPSPROSS', 'HOPPIP', 'HOPPIP'),
    188: ('SKIPLOOM', 'SKIPLOOM', 'FLORAVOL', 'HUBELUPF', 'SKIPLOOM', 'SKIPLOOM'),
    189: ('JUMPLUFF', 'JUMPLUFF', 'COTOVOL', 'PAPUNGHA', 'JUMPLUFF', 'JUMPLUFF'),
    190: ('AIPOM', 'AIPOM', 'CAPUMAIN', 'GRIFFEL', 'AIPOM', 'AIPOM'),
    191: ('SUNKERN', 'SUNKERN', 'TOURNEGRIN', 'SONNKERN', 'SUNKERN', 'SUNKERN'),
    192: ('SUNFLORA', 'SUNFLORA', 'HELIATRONC', 'SONNFLORA', 'SUNFLORA', 'SUNFLORA'),
    193: ('YANMA', 'YANMA', 'YANMA', 'YANMA', 'YANMA', 'YANMA'),
    194: ('WOOPER', 'WOOPER', 'AXOLOTO', 'QUAPSEL', 'WOOPER', 'WOOPER'),
    195: ('QUAGSIRE', 'QUAGSIRE', 'MARAISTE', 'MORLORD', 'QUAGSIRE', 'QUAGSIRE'),
    196: ('ESPEON', 'ESPEON', 'MENTALI', 'PSIANA', 'ESPEON', 'ESPEON'),
    197: ('UMBREON', 'UMBREON', 'NOCTALI', 'NACHTARA', 'UMBREON', 'UMBREON'),
    198: ('MURKROW', 'MURKROW', 'CORNEBRE', 'KRAMURX', 'MURKROW', 'MURKROW'),
    199: ('SLOWKING', 'SLOWKING', 'ROIGADA', 'LASCHOKING', 'SLOWKING', 'SLOWKING'),
    200: ('MISDREAVUS', 'MISDREAVUS', 'FEUFOREVE', 'TRAUNFUGIL', 'MISDREAVUS', 'MISDREAVUS'),
    201: ('UNOWN', 'UNOWN', 'ZARBI', 'ICOGNITO', 'UNOWN', 'UNOWN'),
    202: ('WOBBUFFET', 'WOBBUFFET', 'QULBUTOKE', 'WOINGENAU', 'WOBBUFFET', 'WOBBUFFET'),
    203: ('GIRAFARIG', 'GIRAFARIG', 'GIRAFARIG', 'GIRAFARIG', 'GIRAFARIG', 'GIRAFARIG'),
    204: ('PINECO', 'PINECO', 'POMDEPIK', 'TANNZA', 'PINECO', 'PINECO'),
    205: ('FORRETRESS', 'FORRETRESS', 'FORETRESS', 'FORSTELLA', 'FORRETRESS', 'FORRETRESS'),
    206: ('DUNSPARCE', 'DUNSPARCE', 'INSOLOURDO', 'DUMMISEL', 'DUNSPARCE', 'DUNSPARCE'),
    207: ('GLIGAR', 'GLIGAR', 'SCORPLANE', 'SKORGLA', 'GLIGAR', 'GLIGAR'),
    208: ('STEELIX', 'STEELIX', 'STEELIX', 'STAHLIX', 'STEELIX', 'STEELIX'),
    209: ('SNUBBULL', 'SNUBBULL', 'SNUBBULL', 'SNUBBULL', 'SNUBBULL', 'SNUBBULL'),
    210: ('GRANBULL', 'GRANBULL', 'GRANBULL', 'GRANBULL', 'GRANBULL', 'GRANBULL'),
    211: ('QWILFISH', 'QWILFISH', 'QWILFISH', 'QWILFISH', 'QWILFISH', 'QWILFISH'),
    212: ('SCIZOR', 'SCIZOR', 'CIZAYOX', 'SCHEROX', 'SCIZOR', 'SCIZOR'),
    213: ('SHUCKLE', 'SHUCKLE', 'CARATROC', 'POTTROTT', 'SHUCKLE', 'SHUCKLE'),
    214: ('HERACROSS', 'HERACROSS', 'SCARHINO', 'SKARABORN', 'HERACROSS', 'HERACROSS'),
    215: ('SNEASEL', 'SNEASEL', 'FARFURET', 'SNIEBEL', 'SNEASEL', 'SNEASEL'),
    216: ('TEDDIURSA', 'TEDDIURSA', 'TEDDIURSA', 'TEDDIURSA', 'TEDDIURSA', 'TEDDIURSA'),
    217: ('URSARING', 'URSARING', 'URSARING', 'URSARING', 'URSARING', 'URSARING'),
    218: ('SLUGMA', 'SLUGMA', 'LIMAGMA', 'SCHNECKMAG', 'SLUGMA', 'SLUGMA'),
    219: ('MAGCARGO', 'MAGCARGO', 'VOLCAROPOD', 'MAGCARGO', 'MAGCARGO', 'MAGCARGO'),
    220: ('SWINUB', 'SWINUB', 'MARCACRIN', 'QUIEKEL', 'SWINUB', 'SWINUB'),
    221: ('PILOSWINE', 'PILOSWINE', 'COCHIGNON', 'KEIFEL', 'PILOSWINE', 'PILOSWINE'),
    222: ('CORSOLA', 'CORSOLA', 'CORAYON', 'CORASONN', 'CORSOLA', 'CORSOLA'),
    223: ('REMORAID', 'REMORAID', 'REMORAID', 'REMORAID', 'REMORAID', 'REMORAID'),
    224: ('OCTILLERY', 'OCTILLERY', 'OCTILLERY', 'OCTILLERY', 'OCTILLERY', 'OCTILLERY'),
    225: ('DELIBIRD', 'DELIBIRD', 'CADOIZO', 'BOTOGEL', 'DELIBIRD', 'DELIBIRD'),
    226: ('MANTINE', 'MANTINE', 'DEMANTA', 'MANTAX', 'MANTINE', 'MANTINE'),
    227: ('SKARMORY', 'SKARMORY', 'AIRMURE', 'PANZAERON', 'SKARMORY', 'SKARMORY'),
    228: ('HOUNDOUR', 'HOUNDOUR', 'MALOSSE', 'HUNDUSTER', 'HOUNDOUR', 'HOUNDOUR'),
    229: ('HOUNDOOM', 'HOUNDOOM', 'DEMOLOSSE', 'HUNDEMON', 'HOUNDOOM', 'HOUNDOOM'),
    230: ('KINGDRA', 'KINGDRA', 'HYPOROI', 'SEEDRAKING', 'KINGDRA', 'KINGDRA'),
    231: ('PHANPY', 'PHANPY', 'PHANPY', 'PHANPY', 'PHANPY', 'PHANPY'),
    232: ('DONPHAN', 'DONPHAN', 'DONPHAN', 'DONPHAN', 'DONPHAN', 'DONPHAN'),
    233: ('PORYGON2', 'PORYGON2', 'PORYGON2', 'PORYGON2', 'PORYGON2', 'PORYGON2'),
    234: ('STANTLER', 'STANTLER', 'CERFROUSSE', 'DAMHIRPLEX', 'STANTLER', 'STANTLER'),
    235: ('SMEARGLE', 'SMEARGLE', 'QUEULORIOR', 'FARBEAGLE', 'SMEARGLE', 'SMEARGLE'),
    236: ('TYROGUE', 'TYROGUE', 'DEBUGANT', 'RABAUZ', 'TYROGUE', 'TYROGUE'),
    237: ('HITMONTOP', 'HITMONTOP', 'KAPOERA', 'KAPOERA', 'HITMONTOP', 'HITMONTOP'),
    238: ('SMOOCHUM', 'SMOOCHUM', 'LIPPOUTI', 'KUSSILLA', 'SMOOCHUM', 'SMOOCHUM'),
    239: ('ELEKID', 'ELEKID', 'ELEKID', 'ELEKID', 'ELEKID', 'ELEKID'),
    240: ('MAGBY', 'MAGBY', 'MAGBY', 'MAGBY', 'MAGBY', 'MAGBY'),
    241: ('MILTANK', 'MILTANK', 'ECREMEUH', 'MILTANK', 'MILTANK', 'MILTANK'),
    242: ('BLISSEY', 'BLISSEY', 'LEUPHORIE', 'HEITEIRA', 'BLISSEY', 'BLISSEY'),
    243: ('RAIKOU', 'RAIKOU', 'RAIKOU', 'RAIKOU', 'RAIKOU', 'RAIKOU'),
    244: ('ENTEI', 'ENTEI', 'ENTEI', 'ENTEI', 'ENTEI', 'ENTEI'),
    245: ('SUICUNE', 'SUICUNE', 'SUICUNE', 'SUICUNE', 'SUICUNE', 'SUICUNE'),
    246: ('LARVITAR', 'LARVITAR', 'EMBRYLEX', 'LARVITAR', 'LARVITAR', 'LARVITAR'),
    247: ('PUPITAR', 'PUPITAR', 'YMPHECT', 'PUPITAR', 'PUPITAR', 'PUPITAR'),
    248: ('TYRANITAR', 'TYRANITAR', 'TYRANOCIF', 'DESPOTAR', 'TYRANITAR', 'TYRANITAR'),
    249: ('LUGIA', 'LUGIA', 'LUGIA', 'LUGIA', 'LUGIA', 'LUGIA'),
    250: ('HO_OH', 'HO_OH', 'HO_OH', 'HO_OH', 'HO_OH', 'HO_OH'),
    251: ('CELEBI', 'CELEBI', 'CELEBI', 'CELEBI', 'CELEBI', 'CELEBI'),
    252: ('TREECKO', 'TREECKO', 'ARCKO', 'GECKARBOR', 'TREECKO', 'TREECKO'),
    253: ('GROVYLE', 'GROVYLE', 'MASSKO', 'REPTAIN', 'GROVYLE', 'GROVYLE'),
    254: ('SCEPTILE', 'SCEPTILE', 'JUNGKO', 'GEWALDRO', 'SCEPTILE', 'SCEPTILE'),
    255: ('TORCHIC', 'TORCHIC', 'POUSSIFEU', 'FLEMMLI', 'TORCHIC', 'TORCHIC'),
    256: ('COMBUSKEN', 'COMBUSKEN', 'GALIFEU', 'JUNGGLUT', 'COMBUSKEN', 'COMBUSKEN'),
    257: ('BLAZIKEN', 'BLAZIKEN', 'BRASEGALI', 'LOHGOCK', 'BLAZIKEN', 'BLAZIKEN'),
    258: ('MUDKIP', 'MUDKIP', 'GOBOU', 'HYDROPI', 'MUDKIP', 'MUDKIP'),
    259: ('MARSHTOMP', 'MARSHTOMP', 'FLOBIO', 'MOORABBEL', 'MARSHTOMP', 'MARSHTOMP'),
    260: ('SWAMPERT', 'SWAMPERT', 'LAGGRON', 'SUMPEX', 'SWAMPERT', 'SWAMPERT'),
    261: ('POOCHYENA', 'POOCHYENA', 'MEDHYENA', 'FIFFYEN', 'POOCHYENA', 'POOCHYENA'),
    262: ('MIGHTYENA', 'MIGHTYENA', 'GRAHYENA', 'MAGNAYEN', 'MIGHTYENA', 'MIGHTYENA'),
    263: ('ZIGZAGOON', 'ZIGZAGOON', 'ZIGZATON', 'ZIGZACHS', 'ZIGZAGOON', 'ZIGZAGOON'),
    264: ('LINOONE', 'LINOONE', 'LINEON', 'GERADAKS', 'LINOONE', 'LINOONE'),
    265: ('WURMPLE', 'WURMPLE', 'CHENIPOTTE', 'WAUMPEL', 'WURMPLE', 'WURMPLE'),
    266: ('SILCOON', 'SILCOON', 'ARMULYS', 'SCHALOKO', 'SILCOON', 'SILCOON'),
    267: ('BEAUTIFLY', 'BEAUTIFLY', 'CHARMILLON', 'PAPINELLA', 'BEAUTIFLY', 'BEAUTIFLY'),
    268: ('CASCOON', 'CASCOON', 'BLINDALYS', 'PANEKON', 'CASCOON', 'CASCOON'),
    269: ('DUSTOX', 'DUSTOX', 'PAPINOX', 'PUDOX', 'DUSTOX', 'DUSTOX'),
    270: ('LOTAD', 'LOTAD', 'NENUPIOT', 'LOTURZEL', 'LOTAD', 'LOTAD'),
    271: ('LOMBRE', 'LOMBRE', 'LOMBRE', 'LOMBRERO', 'LOMBRE', 'LOMBRE'),
    272: ('LUDICOLO', 'LUDICOLO', 'LUDICOLO', 'KAPPALORES', 'LUDICOLO', 'LUDICOLO'),
    273: ('SEEDOT', 'SEEDOT', 'GRAINIPIOT', 'SAMURZEL', 'SEEDOT', 'SEEDOT'),
    274: ('NUZLEAF', 'NUZLEAF', 'PIFEUIL', 'BLANAS', 'NUZLEAF', 'NUZLEAF'),
    275: ('SHIFTRY', 'SHIFTRY', 'TENGALICE', 'TENGULIST', 'SHIFTRY', 'SHIFTRY'),
    276: ('TAILLOW', 'TAILLOW', 'NIRONDELLE', 'SCHWALBINI', 'TAILLOW', 'TAILLOW'),
    277: ('SWELLOW', 'SWELLOW', 'HELEDELLE', 'SCHWALBOSS', 'SWELLOW', 'SWELLOW'),
    278: ('WINGULL', 'WINGULL', 'GOELISE', 'WINGULL', 'WINGULL', 'WINGULL'),
    279: ('PELIPPER', 'PELIPPER', 'BEKIPAN', 'PELIPPER', 'PELIPPER', 'PELIPPER'),
    280: ('RALTS', 'RALTS', 'TARSAL', 'TRASLA', 'RALTS', 'RALTS'),
    281: ('KIRLIA', 'KIRLIA', 'KIRLIA', 'KIRLIA', 'KIRLIA', 'KIRLIA'),
    282: ('GARDEVOIR', 'GARDEVOIR', 'GARDEVOIR', 'GUARDEVOIR', 'GARDEVOIR', 'GARDEVOIR'),
    283: ('SURSKIT', 'SURSKIT', 'ARAKDO', 'GEHWEIHER', 'SURSKIT', 'SURSKIT'),
    284: ('MASQUERAIN', 'MASQUERAIN', 'MASKADRA', 'MASKEREGEN', 'MASQUERAIN', 'MASQUERAIN'),
    285: ('SHROOMISH', 'SHROOMISH', 'BALIGNON', 'KNILZ', 'SHROOMISH', 'SHROOMISH'),
    286: ('BRELOOM', 'BRELOOM', 'CHAPIGNON', 'KAPILZ', 'BRELOOM', 'BRELOOM'),
    287: ('SLAKOTH', 'SLAKOTH', 'PARECOOL', 'BUMMELZ', 'SLAKOTH', 'SLAKOTH'),
    288: ('VIGOROTH', 'VIGOROTH', 'VIGOROTH', 'MUNTIER', 'VIGOROTH', 'VIGOROTH'),
    289: ('SLAKING', 'SLAKING', 'MONAFLEMIT', 'LETARKING', 'SLAKING', 'SLAKING'),
    290: ('NINCADA', 'NINCADA', 'NINGALE', 'NINCADA', 'NINCADA', 'NINCADA'),
    291: ('NINJASK', 'NINJASK', 'NINJASK', 'NINJASK', 'NINJASK', 'NINJASK'),
    292: ('SHEDINJA', 'SHEDINJA', 'MUNJA', 'NINJATOM', 'SHEDINJA', 'SHEDINJA'),
    293: ('WHISMUR', 'WHISMUR', 'CHUCHMUR', 'FLURMEL', 'WHISMUR', 'WHISMUR'),
    294: ('LOUDRED', 'LOUDRED', 'RAMBOUM', 'KRAKEELO', 'LOUDRED', 'LOUDRED'),
    295: ('EXPLOUD', 'EXPLOUD', 'BROUHABAM', 'KRAWUMMS', 'EXPLOUD', 'EXPLOUD'),
    296: ('MAKUHITA', 'MAKUHITA', 'MAKUHITA', 'MAKUHITA', 'MAKUHITA', 'MAKUHITA'),
    297: ('HARIYAMA', 'HARIYAMA', 'HARIYAMA', 'HARIYAMA', 'HARIYAMA', 'HARIYAMA'),
    298: ('AZURILL', 'AZURILL', 'AZURILL', 'AZURILL', 'AZURILL', 'AZURILL'),
    299: ('NOSEPASS', 'NOSEPASS', 'TARINOR', 'NASGNET', 'NOSEPASS', 'NOSEPASS'),
    300: ('SKITTY', 'SKITTY', 'SKITTY', 'ENECO', 'SKITTY', 'SKITTY'),
    301: ('DELCATTY', 'DELCATTY', 'DELCATTY', 'ENEKORO', 'DELCATTY', 'DELCATTY'),
    302: ('SABLEYE', 'SABLEYE', 'TENEFIX', 'ZOBIRIS', 'SABLEYE', 'SABLEYE'),
    303: ('MAWILE', 'MAWILE', 'MYSDIBULE', 'FLUNKIFER', 'MAWILE', 'MAWILE'),
    304: ('ARON', 'ARON', 'GALEKID', 'STOLLUNIOR', 'ARON', 'ARON'),
    305: ('LAIRON', 'LAIRON', 'GALEGON', 'STOLLRAK', 'LAIRON', 'LAIRON'),
    306: ('AGGRON', 'AGGRON', 'GALEKING', 'STOLLOSS', 'AGGRON', 'AGGRON'),
    307: ('MEDITITE', 'MEDITITE', 'MEDITIKKA', 'MEDITIE', 'MEDITITE', 'MEDITITE'),
    308: ('MEDICHAM', 'MEDICHAM', 'CHARMINA', 'MEDITALIS', 'MEDICHAM', 'MEDICHAM'),
    309: ('ELECTRIKE', 'ELECTRIKE', 'DYNAVOLT', 'FRIZELBLIZ', 'ELECTRIKE', 'ELECTRIKE'),
    310: ('MANECTRIC', 'MANECTRIC', 'ELECSPRINT', 'VOLTENSO', 'MANECTRIC', 'MANECTRIC'),
    311: ('PLUSLE', 'PLUSLE', 'POSIPI', 'PLUSLE', 'PLUSLE', 'PLUSLE'),
    312: ('MINUN', 'MINUN', 'NEGAPI', 'MINUN', 'MINUN', 'MINUN'),
    313: ('VOLBEAT', 'VOLBEAT', 'MUCIOLE', 'VOLBEAT', 'VOLBEAT', 'VOLBEAT'),
    314: ('ILLUMISE', 'ILLUMISE', 'LUMIVOLE', 'ILLUMISE', 'ILLUMISE', 'ILLUMISE'),
    315: ('ROSELIA', 'ROSELIA', 'ROSELIA', 'ROSELIA', 'ROSELIA', 'ROSELIA'),
    316: ('GULPIN', 'GULPIN', 'GLOUPTI', 'SCHLUPPUCK', 'GULPIN', 'GULPIN'),
    317: ('SWALOT', 'SWALOT', 'AVALTOUT', 'SCHLUKWECH', 'SWALOT', 'SWALOT'),
    318: ('CARVANHA', 'CARVANHA', 'CARVANHA', 'KANIVANHA', 'CARVANHA', 'CARVANHA'),
    319: ('SHARPEDO', 'SHARPEDO', 'SHARPEDO', 'TOHAIDO', 'SHARPEDO', 'SHARPEDO'),
    320: ('WAILMER', 'WAILMER', 'WAILMER', 'WAILMER', 'WAILMER', 'WAILMER'),
    321: ('WAILORD', 'WAILORD', 'WAILORD', 'WAILORD', 'WAILORD', 'WAILORD'),
    322: ('NUMEL', 'NUMEL', 'CHAMALLOT', 'CAMAUB', 'NUMEL', 'NUMEL'),
    323: ('CAMERUPT', 'CAMERUPT', 'CAMERUPT', 'CAMERUPT', 'CAMERUPT', 'CAMERUPT'),
    324: ('TORKOAL', 'TORKOAL', 'CHARTOR', 'QURTEL', 'TORKOAL', 'TORKOAL'),
    325: ('SPOINK', 'SPOINK', 'SPOINK', 'SPOINK', 'SPOINK', 'SPOINK'),
    326: ('GRUMPIG', 'GRUMPIG', 'GRORET', 'GROINK', 'GRUMPIG', 'GRUMPIG'),
    327: ('SPINDA', 'SPINDA', 'SPINDA', 'PANDIR', 'SPINDA', 'SPINDA'),
    328: ('TRAPINCH', 'TRAPINCH', 'KRAKNOIX', 'KNACKLION', 'TRAPINCH', 'TRAPINCH'),
    329: ('VIBRAVA', 'VIBRAVA', 'VIBRANINF', 'VIBRAVA', 'VIBRAVA', 'VIBRAVA'),
    330: ('FLYGON', 'FLYGON', 'LIBEGON', 'LIBELLDRA', 'FLYGON', 'FLYGON'),
    331: ('CACNEA', 'CACNEA', 'CACNEA', 'TUSKA', 'CACNEA', 'CACNEA'),
    332: ('CACTURNE', 'CACTURNE', 'CACTURNE', 'NOKTUSKA', 'CACTURNE', 'CACTURNE'),
    333: ('SWABLU', 'SWABLU', 'TYLTON', 'WABLU', 'SWABLU', 'SWABLU'),
    334: ('ALTARIA', 'ALTARIA', 'ALTARIA', 'ALTARIA', 'ALTARIA', 'ALTARIA'),
    335: ('ZANGOOSE', 'ZANGOOSE', 'MANGRIFF', 'SENGO', 'ZANGOOSE', 'ZANGOOSE'),
    336: ('SEVIPER', 'SEVIPER', 'SEVIPER', 'VIPITIS', 'SEVIPER', 'SEVIPER'),
    337: ('LUNATONE', 'LUNATONE', 'SELEROC', 'LUNASTEIN', 'LUNATONE', 'LUNATONE'),
    338: ('SOLROCK', 'SOLROCK', 'SOLAROC', 'SONNFEL', 'SOLROCK', 'SOLROCK'),
    339: ('BARBOACH', 'BARBOACH', 'BARLOCHE', 'SCHMERBE', 'BARBOACH', 'BARBOACH'),
    340: ('WHISCASH', 'WHISCASH', 'BARBICHA', 'WELSAR', 'WHISCASH', 'WHISCASH'),
    341: ('CORPHISH', 'CORPHISH', 'ECRAPINCE', 'KREBSCORPS', 'CORPHISH', 'CORPHISH'),
    342: ('CRAWDAUNT', 'CRAWDAUNT', 'COLHOMARD', 'KREBUTACK', 'CRAWDAUNT', 'CRAWDAUNT'),
    343: ('BALTOY', 'BALTOY', 'BALBUTO', 'PUPPANCE', 'BALTOY', 'BALTOY'),
    344: ('CLAYDOL', 'CLAYDOL', 'KAORINE', 'LEPUMENTAS', 'CLAYDOL', 'CLAYDOL'),
    345: ('LILEEP', 'LILEEP', 'LILIA', 'LILIEP', 'LILEEP', 'LILEEP'),
    346: ('CRADILY', 'CRADILY', 'VACILYS', 'WIELIE', 'CRADILY', 'CRADILY'),
    347: ('ANORITH', 'ANORITH', 'ANORITH', 'ANORITH', 'ANORITH', 'ANORITH'),
    348: ('ARMALDO', 'ARMALDO', 'ARMALDO', 'ARMALDO', 'ARMALDO', 'ARMALDO'),
    349: ('FEEBAS', 'FEEBAS', 'BARPAU', 'BARSCHWA', 'FEEBAS', 'FEEBAS'),
    350: ('MILOTIC', 'MILOTIC', 'MILOBELLUS', 'MILOTIC', 'MILOTIC', 'MILOTIC'),
    351: ('CASTFORM', 'CASTFORM', 'MORPHEO', 'FORMEO', 'CASTFORM', 'CASTFORM'),
    352: ('KECLEON', 'KECLEON', 'KECLEON', 'KECLEON', 'KECLEON', 'KECLEON'),
    353: ('SHUPPET', 'SHUPPET', 'POLICHOMBR', 'SHUPPET', 'SHUPPET', 'SHUPPET'),
    354: ('BANETTE', 'BANETTE', 'BRANETTE', 'BANETTE', 'BANETTE', 'BANETTE'),
    355: ('DUSKULL', 'DUSKULL', 'SKELENOX', 'ZWIRRLICHT', 'DUSKULL', 'DUSKULL'),
    356: ('DUSCLOPS', 'DUSCLOPS', 'TERACLOPE', 'ZWIRRKLOP', 'DUSCLOPS', 'DUSCLOPS'),
    357: ('TROPIUS', 'TROPIUS', 'TROPIUS', 'TROPIUS', 'TROPIUS', 'TROPIUS'),
    358: ('CHIMECHO', 'CHIMECHO', 'EOKO', 'PALIMPALIM', 'CHIMECHO', 'CHIMECHO'),
    359: ('ABSOL', 'ABSOL', 'ABSOL', 'ABSOL', 'ABSOL', 'ABSOL'),
    360: ('WYNAUT', 'WYNAUT', 'OKEOKE', 'ISSO', 'WYNAUT', 'WYNAUT'),
    361: ('SNORUNT', 'SNORUNT', 'STALGAMIN', 'SCHNEPPKE', 'SNORUNT', 'SNORUNT'),
    362: ('GLALIE', 'GLALIE', 'ONIGLALI', 'FIRNONTOR', 'GLALIE', 'GLALIE'),
    363: ('SPHEAL', 'SPHEAL', 'OBALIE', 'SEEMOPS', 'SPHEAL', 'SPHEAL'),
    364: ('SEALEO', 'SEALEO', 'PHOGLEUR', 'SEEJONG', 'SEALEO', 'SEALEO'),
    365: ('WALREIN', 'WALREIN', 'KAIMORSE', 'WALRAISA', 'WALREIN', 'WALREIN'),
    366: ('CLAMPERL', 'CLAMPERL', 'COQUIPERL', 'PERLU', 'CLAMPERL', 'CLAMPERL'),
    367: ('HUNTAIL', 'HUNTAIL', 'SERPANG', 'AALABYSS', 'HUNTAIL', 'HUNTAIL'),
    368: ('GOREBYSS', 'GOREBYSS', 'ROSABYSS', 'SAGANABYSS', 'GOREBYSS', 'GOREBYSS'),
    369: ('RELICANTH', 'RELICANTH', 'RELICANTH', 'RELICANTH', 'RELICANTH', 'RELICANTH'),
    370: ('LUVDISC', 'LUVDISC', 'LOVDISC', 'LIEBISKUS', 'LUVDISC', 'LUVDISC'),
    371: ('BAGON', 'BAGON', 'DRABY', 'KINDWURM', 'BAGON', 'BAGON'),
    372: ('SHELGON', 'SHELGON', 'DRACKHAUS', 'DRASCHEL', 'SHELGON', 'SHELGON'),
    373: ('SALAMENCE', 'SALAMENCE', 'DRATTAK', 'BRUTALANDA', 'SALAMENCE', 'SALAMENCE'),
    374: ('BELDUM', 'BELDUM', 'TERHAL', 'TANHEL', 'BELDUM', 'BELDUM'),
    375: ('METANG', 'METANG', 'METANG', 'METANG', 'METANG', 'METANG'),
    376: ('METAGROSS', 'METAGROSS', 'METALOSSE', 'METAGROSS', 'METAGROSS', 'METAGROSS'),
    377: ('REGIROCK', 'REGIROCK', 'REGIROCK', 'REGIROCK', 'REGIROCK', 'REGIROCK'),
    378: ('REGICE', 'REGICE', 'REGICE', 'REGICE', 'REGICE', 'REGICE'),
    379: ('REGISTEEL', 'REGISTEEL', 'REGISTEEL', 'REGISTEEL', 'REGISTEEL', 'REGISTEEL'),
    380: ('LATIAS', 'LATIAS', 'LATIAS', 'LATIAS', 'LATIAS', 'LATIAS'),
    381: ('LATIOS', 'LATIOS', 'LATIOS', 'LATIOS', 'LATIOS', 'LATIOS'),
    382: ('KYOGRE', 'KYOGRE', 'KYOGRE', 'KYOGRE', 'KYOGRE', 'KYOGRE'),
    383: ('GROUDON', 'GROUDON', 'GROUDON', 'GROUDON', 'GROUDON', 'GROUDON'),
    384: ('RAYQUAZA', 'RAYQUAZA', 'RAYQUAZA', 'RAYQUAZA', 'RAYQUAZA', 'RAYQUAZA'),
    385: ('JIRACHI', 'JIRACHI', 'JIRACHI', 'JIRACHI', 'JIRACHI', 'JIRACHI'),
    386: ('DEOXYS', 'DEOXYS', 'DEOXYS', 'DEOXYS', 'DEOXYS', 'DEOXYS'),
}

# num, slug, display, tipo, evolucionaA, nivel
DEX = [
    (1, 'bulbasaur', 'BULBASAUR', 'planta', 2, 16),
    (2, 'ivysaur', 'IVYSAUR', 'planta', 3, 32),
    (3, 'venusaur', 'VENUSAUR', 'planta', 0, 0),
    (4, 'charmander', 'CHARMANDER', 'fuego', 5, 16),
    (5, 'charmeleon', 'CHARMELEON', 'fuego', 6, 36),
    (6, 'charizard', 'CHARIZARD', 'fuego', 0, 0),
    (7, 'squirtle', 'SQUIRTLE', 'agua', 8, 16),
    (8, 'wartortle', 'WARTORTLE', 'agua', 9, 36),
    (9, 'blastoise', 'BLASTOISE', 'agua', 0, 0),
    (10, 'caterpie', 'CATERPIE', 'bicho', 11, 7),
    (11, 'metapod', 'METAPOD', 'bicho', 12, 10),
    (12, 'butterfree', 'BUTTERFREE', 'bicho', 0, 0),
    (13, 'weedle', 'WEEDLE', 'bicho', 14, 7),
    (14, 'kakuna', 'KAKUNA', 'bicho', 15, 10),
    (15, 'beedrill', 'BEEDRILL', 'bicho', 0, 0),
    (16, 'pidgey', 'PIDGEY', 'normal', 17, 18),
    (17, 'pidgeotto', 'PIDGEOTTO', 'normal', 18, 36),
    (18, 'pidgeot', 'PIDGEOT', 'normal', 0, 0),
    (19, 'rattata', 'RATTATA', 'normal', 20, 20),
    (20, 'raticate', 'RATICATE', 'normal', 0, 0),
    (21, 'spearow', 'SPEAROW', 'normal', 22, 20),
    (22, 'fearow', 'FEAROW', 'normal', 0, 0),
    (23, 'ekans', 'EKANS', 'veneno', 24, 22),
    (24, 'arbok', 'ARBOK', 'veneno', 0, 0),
    (25, 'pikachu', 'PIKACHU', 'electrico', 26, 30),
    (26, 'raichu', 'RAICHU', 'electrico', 0, 0),
    (27, 'sandshrew', 'SANDSHREW', 'tierra', 28, 22),
    (28, 'sandslash', 'SANDSLASH', 'tierra', 0, 0),
    (29, 'nidoranf', 'NIDORAN H', 'veneno', 30, 16),
    (30, 'nidorina', 'NIDORINA', 'veneno', 31, 30),
    (31, 'nidoqueen', 'NIDOQUEEN', 'veneno', 0, 0),
    (32, 'nidoranm', 'NIDORAN M', 'veneno', 33, 16),
    (33, 'nidorino', 'NIDORINO', 'veneno', 34, 30),
    (34, 'nidoking', 'NIDOKING', 'veneno', 0, 0),
    (35, 'clefairy', 'CLEFAIRY', 'normal', 36, 30),
    (36, 'clefable', 'CLEFABLE', 'normal', 0, 0),
    (37, 'vulpix', 'VULPIX', 'fuego', 38, 30),
    (38, 'ninetales', 'NINETALES', 'fuego', 0, 0),
    (39, 'jigglypuff', 'JIGGLYPUFF', 'normal', 40, 30),
    (40, 'wigglytuff', 'WIGGLYTUFF', 'normal', 0, 0),
    (41, 'zubat', 'ZUBAT', 'veneno', 42, 22),
    (42, 'golbat', 'GOLBAT', 'veneno', 0, 0),
    (43, 'oddish', 'ODDISH', 'planta', 44, 21),
    (44, 'gloom', 'GLOOM', 'planta', 45, 36),
    (45, 'vileplume', 'VILEPLUME', 'planta', 0, 0),
    (46, 'paras', 'PARAS', 'bicho', 47, 24),
    (47, 'parasect', 'PARASECT', 'bicho', 0, 0),
    (48, 'venonat', 'VENONAT', 'bicho', 49, 31),
    (49, 'venomoth', 'VENOMOTH', 'bicho', 0, 0),
    (50, 'diglett', 'DIGLETT', 'tierra', 51, 26),
    (51, 'dugtrio', 'DUGTRIO', 'tierra', 0, 0),
    (52, 'meowth', 'MEOWTH', 'normal', 53, 28),
    (53, 'persian', 'PERSIAN', 'normal', 0, 0),
    (54, 'psyduck', 'PSYDUCK', 'agua', 55, 33),
    (55, 'golduck', 'GOLDUCK', 'agua', 0, 0),
    (56, 'mankey', 'MANKEY', 'lucha', 57, 28),
    (57, 'primeape', 'PRIMEAPE', 'lucha', 0, 0),
    (58, 'growlithe', 'GROWLITHE', 'fuego', 59, 30),
    (59, 'arcanine', 'ARCANINE', 'fuego', 0, 0),
    (60, 'poliwag', 'POLIWAG', 'agua', 61, 25),
    (61, 'poliwhirl', 'POLIWHIRL', 'agua', 62, 36),
    (62, 'poliwrath', 'POLIWRATH', 'agua', 0, 0),
    (63, 'abra', 'ABRA', 'psiquico', 64, 16),
    (64, 'kadabra', 'KADABRA', 'psiquico', 65, 40),
    (65, 'alakazam', 'ALAKAZAM', 'psiquico', 0, 0),
    (66, 'machop', 'MACHOP', 'lucha', 67, 28),
    (67, 'machoke', 'MACHOKE', 'lucha', 68, 40),
    (68, 'machamp', 'MACHAMP', 'lucha', 0, 0),
    (69, 'bellsprout', 'BELLSPROUT', 'planta', 70, 21),
    (70, 'weepinbell', 'WEEPINBELL', 'planta', 71, 36),
    (71, 'victreebel', 'VICTREEBEL', 'planta', 0, 0),
    (72, 'tentacool', 'TENTACOOL', 'agua', 73, 30),
    (73, 'tentacruel', 'TENTACRUEL', 'agua', 0, 0),
    (74, 'geodude', 'GEODUDE', 'roca', 75, 25),
    (75, 'graveler', 'GRAVELER', 'roca', 76, 40),
    (76, 'golem', 'GOLEM', 'roca', 0, 0),
    (77, 'ponyta', 'PONYTA', 'fuego', 78, 40),
    (78, 'rapidash', 'RAPIDASH', 'fuego', 0, 0),
    (79, 'slowpoke', 'SLOWPOKE', 'agua', 80, 37),
    (80, 'slowbro', 'SLOWBRO', 'agua', 0, 0),
    (81, 'magnemite', 'MAGNEMITE', 'electrico', 82, 30),
    (82, 'magneton', 'MAGNETON', 'electrico', 0, 0),
    (83, 'farfetchd', 'FARFETCHD', 'normal', 0, 0),
    (84, 'doduo', 'DODUO', 'normal', 85, 31),
    (85, 'dodrio', 'DODRIO', 'normal', 0, 0),
    (86, 'seel', 'SEEL', 'agua', 87, 34),
    (87, 'dewgong', 'DEWGONG', 'agua', 0, 0),
    (88, 'grimer', 'GRIMER', 'veneno', 89, 38),
    (89, 'muk', 'MUK', 'veneno', 0, 0),
    (90, 'shellder', 'SHELLDER', 'agua', 91, 30),
    (91, 'cloyster', 'CLOYSTER', 'agua', 0, 0),
    (92, 'gastly', 'GASTLY', 'fantasma', 93, 25),
    (93, 'haunter', 'HAUNTER', 'fantasma', 94, 40),
    (94, 'gengar', 'GENGAR', 'fantasma', 0, 0),
    (95, 'onix', 'ONIX', 'roca', 0, 0),
    (96, 'drowzee', 'DROWZEE', 'psiquico', 97, 26),
    (97, 'hypno', 'HYPNO', 'psiquico', 0, 0),
    (98, 'krabby', 'KRABBY', 'agua', 99, 28),
    (99, 'kingler', 'KINGLER', 'agua', 0, 0),
    (100, 'voltorb', 'VOLTORB', 'electrico', 101, 30),
    (101, 'electrode', 'ELECTRODE', 'electrico', 0, 0),
    (102, 'exeggcute', 'EXEGGCUTE', 'planta', 103, 30),
    (103, 'exeggutor', 'EXEGGUTOR', 'planta', 0, 0),
    (104, 'cubone', 'CUBONE', 'tierra', 105, 28),
    (105, 'marowak', 'MAROWAK', 'tierra', 0, 0),
    (106, 'hitmonlee', 'HITMONLEE', 'lucha', 0, 0),
    (107, 'hitmonchan', 'HITMONCHAN', 'lucha', 0, 0),
    (108, 'lickitung', 'LICKITUNG', 'normal', 0, 0),
    (109, 'koffing', 'KOFFING', 'veneno', 110, 35),
    (110, 'weezing', 'WEEZING', 'veneno', 0, 0),
    (111, 'rhyhorn', 'RHYHORN', 'tierra', 112, 42),
    (112, 'rhydon', 'RHYDON', 'tierra', 0, 0),
    (113, 'chansey', 'CHANSEY', 'normal', 0, 0),
    (114, 'tangela', 'TANGELA', 'planta', 0, 0),
    (115, 'kangaskhan', 'KANGASKHAN', 'normal', 0, 0),
    (116, 'horsea', 'HORSEA', 'agua', 117, 32),
    (117, 'seadra', 'SEADRA', 'agua', 0, 0),
    (118, 'goldeen', 'GOLDEEN', 'agua', 119, 33),
    (119, 'seaking', 'SEAKING', 'agua', 0, 0),
    (120, 'staryu', 'STARYU', 'agua', 121, 30),
    (121, 'starmie', 'STARMIE', 'agua', 0, 0),
    (122, 'mrmime', 'MR. MIME', 'psiquico', 0, 0),
    (123, 'scyther', 'SCYTHER', 'bicho', 0, 0),
    (124, 'jynx', 'JYNX', 'hielo', 0, 0),
    (125, 'electabuzz', 'ELECTABUZZ', 'electrico', 0, 0),
    (126, 'magmar', 'MAGMAR', 'fuego', 0, 0),
    (127, 'pinsir', 'PINSIR', 'bicho', 0, 0),
    (128, 'tauros', 'TAUROS', 'normal', 0, 0),
    (129, 'magikarp', 'MAGIKARP', 'agua', 130, 20),
    (130, 'gyarados', 'GYARADOS', 'agua', 0, 0),
    (131, 'lapras', 'LAPRAS', 'agua', 0, 0),
    (132, 'ditto', 'DITTO', 'normal', 0, 0),
    (133, 'eevee', 'EEVEE', 'normal', 134, 30),  # rama al azar en el juego
    (134, 'vaporeon', 'VAPOREON', 'agua', 0, 0),
    (135, 'jolteon', 'JOLTEON', 'electrico', 0, 0),
    (136, 'flareon', 'FLAREON', 'fuego', 0, 0),
    (137, 'porygon', 'PORYGON', 'normal', 0, 0),
    (138, 'omanyte', 'OMANYTE', 'roca', 139, 40),
    (139, 'omastar', 'OMASTAR', 'roca', 0, 0),
    (140, 'kabuto', 'KABUTO', 'roca', 141, 40),
    (141, 'kabutops', 'KABUTOPS', 'roca', 0, 0),
    (142, 'aerodactyl', 'AERODACTYL', 'roca', 0, 0),
    (143, 'snorlax', 'SNORLAX', 'normal', 0, 0),
    (144, 'articuno', 'ARTICUNO', 'hielo', 0, 0),
    (145, 'zapdos', 'ZAPDOS', 'electrico', 0, 0),
    (146, 'moltres', 'MOLTRES', 'fuego', 0, 0),
    (147, 'dratini', 'DRATINI', 'dragon', 148, 30),
    (148, 'dragonair', 'DRAGONAIR', 'dragon', 149, 55),
    (149, 'dragonite', 'DRAGONITE', 'dragon', 0, 0),
    (150, 'mewtwo', 'MEWTWO', 'psiquico', 0, 0),
    (151, 'mew', 'MEW', 'psiquico', 0, 0),
    (152, 'chikorita', 'CHIKORITA', 'planta', 153, 16),
    (153, 'bayleef', 'BAYLEEF', 'planta', 154, 32),
    (154, 'meganium', 'MEGANIUM', 'planta', 0, 0),
    (155, 'cyndaquil', 'CYNDAQUIL', 'fuego', 156, 14),
    (156, 'quilava', 'QUILAVA', 'fuego', 157, 36),
    (157, 'typhlosion', 'TYPHLOSION', 'fuego', 0, 0),
    (158, 'totodile', 'TOTODILE', 'agua', 159, 18),
    (159, 'croconaw', 'CROCONAW', 'agua', 160, 30),
    (160, 'feraligatr', 'FERALIGATR', 'agua', 0, 0),
    (161, 'sentret', 'SENTRET', 'normal', 162, 15),
    (162, 'furret', 'FURRET', 'normal', 0, 0),
    (163, 'hoothoot', 'HOOTHOOT', 'normal', 164, 20),
    (164, 'noctowl', 'NOCTOWL', 'normal', 0, 0),
    (165, 'ledyba', 'LEDYBA', 'bicho', 166, 18),
    (166, 'ledian', 'LEDIAN', 'bicho', 0, 0),
    (167, 'spinarak', 'SPINARAK', 'bicho', 168, 22),
    (168, 'ariados', 'ARIADOS', 'bicho', 0, 0),
    (169, 'crobat', 'CROBAT', 'veneno', 0, 0),
    (170, 'chinchou', 'CHINCHOU', 'agua', 171, 27),
    (171, 'lanturn', 'LANTURN', 'agua', 0, 0),
    (172, 'pichu', 'PICHU', 'electrico', 25, 10),
    (173, 'cleffa', 'CLEFFA', 'normal', 35, 10),
    (174, 'igglybuff', 'IGGLYBUFF', 'normal', 39, 10),
    (175, 'togepi', 'TOGEPI', 'normal', 176, 10),
    (176, 'togetic', 'TOGETIC', 'normal', 0, 0),
    (177, 'natu', 'NATU', 'psiquico', 178, 25),
    (178, 'xatu', 'XATU', 'psiquico', 0, 0),
    (179, 'mareep', 'MAREEP', 'electrico', 180, 15),
    (180, 'flaaffy', 'FLAAFFY', 'electrico', 181, 30),
    (181, 'ampharos', 'AMPHAROS', 'electrico', 0, 0),
    (182, 'bellossom', 'BELLOSSOM', 'planta', 0, 0),
    (183, 'marill', 'MARILL', 'agua', 184, 18),
    (184, 'azumarill', 'AZUMARILL', 'agua', 0, 0),
    (185, 'sudowoodo', 'SUDOWOODO', 'roca', 0, 0),
    (186, 'politoed', 'POLITOED', 'agua', 0, 0),
    (187, 'hoppip', 'HOPPIP', 'planta', 188, 18),
    (188, 'skiploom', 'SKIPLOOM', 'planta', 189, 27),
    (189, 'jumpluff', 'JUMPLUFF', 'planta', 0, 0),
    (190, 'aipom', 'AIPOM', 'normal', 0, 0),
    (191, 'sunkern', 'SUNKERN', 'planta', 192, 20),
    (192, 'sunflora', 'SUNFLORA', 'planta', 0, 0),
    (193, 'yanma', 'YANMA', 'bicho', 0, 0),
    (194, 'wooper', 'WOOPER', 'agua', 195, 20),
    (195, 'quagsire', 'QUAGSIRE', 'agua', 0, 0),
    (196, 'espeon', 'ESPEON', 'psiquico', 0, 0),
    (197, 'umbreon', 'UMBREON', 'siniestro', 0, 0),
    (198, 'murkrow', 'MURKROW', 'siniestro', 0, 0),
    (199, 'slowking', 'SLOWKING', 'agua', 0, 0),
    (200, 'misdreavus', 'MISDREAVUS', 'fantasma', 0, 0),
    (201, 'unown', 'UNOWN', 'psiquico', 0, 0),
    (202, 'wobbuffet', 'WOBBUFFET', 'psiquico', 0, 0),
    (203, 'girafarig', 'GIRAFARIG', 'normal', 0, 0),
    (204, 'pineco', 'PINECO', 'bicho', 205, 31),
    (205, 'forretress', 'FORRETRESS', 'bicho', 0, 0),
    (206, 'dunsparce', 'DUNSPARCE', 'normal', 0, 0),
    (207, 'gligar', 'GLIGAR', 'tierra', 0, 0),
    (208, 'steelix', 'STEELIX', 'tierra', 0, 0),
    (209, 'snubbull', 'SNUBBULL', 'normal', 210, 23),
    (210, 'granbull', 'GRANBULL', 'normal', 0, 0),
    (211, 'qwilfish', 'QWILFISH', 'agua', 0, 0),
    (212, 'scizor', 'SCIZOR', 'bicho', 0, 0),
    (213, 'shuckle', 'SHUCKLE', 'bicho', 0, 0),
    (214, 'heracross', 'HERACROSS', 'bicho', 0, 0),
    (215, 'sneasel', 'SNEASEL', 'siniestro', 0, 0),
    (216, 'teddiursa', 'TEDDIURSA', 'normal', 217, 30),
    (217, 'ursaring', 'URSARING', 'normal', 0, 0),
    (218, 'slugma', 'SLUGMA', 'fuego', 219, 38),
    (219, 'magcargo', 'MAGCARGO', 'fuego', 0, 0),
    (220, 'swinub', 'SWINUB', 'hielo', 221, 33),
    (221, 'piloswine', 'PILOSWINE', 'hielo', 0, 0),
    (222, 'corsola', 'CORSOLA', 'agua', 0, 0),
    (223, 'remoraid', 'REMORAID', 'agua', 224, 25),
    (224, 'octillery', 'OCTILLERY', 'agua', 0, 0),
    (225, 'delibird', 'DELIBIRD', 'hielo', 0, 0),
    (226, 'mantine', 'MANTINE', 'agua', 0, 0),
    (227, 'skarmory', 'SKARMORY', 'acero', 0, 0),
    (228, 'houndour', 'HOUNDOUR', 'siniestro', 229, 24),
    (229, 'houndoom', 'HOUNDOOM', 'siniestro', 0, 0),
    (230, 'kingdra', 'KINGDRA', 'agua', 0, 0),
    (231, 'phanpy', 'PHANPY', 'tierra', 232, 25),
    (232, 'donphan', 'DONPHAN', 'tierra', 0, 0),
    (233, 'porygon2', 'PORYGON2', 'normal', 0, 0),
    (234, 'stantler', 'STANTLER', 'normal', 0, 0),
    (235, 'smeargle', 'SMEARGLE', 'normal', 0, 0),
    (236, 'tyrogue', 'TYROGUE', 'lucha', 0, 0),
    (237, 'hitmontop', 'HITMONTOP', 'lucha', 0, 0),
    (238, 'smoochum', 'SMOOCHUM', 'hielo', 124, 30),
    (239, 'elekid', 'ELEKID', 'electrico', 125, 30),
    (240, 'magby', 'MAGBY', 'fuego', 126, 30),
    (241, 'miltank', 'MILTANK', 'normal', 0, 0),
    (242, 'blissey', 'BLISSEY', 'normal', 0, 0),
    (243, 'raikou', 'RAIKOU', 'electrico', 0, 0),
    (244, 'entei', 'ENTEI', 'fuego', 0, 0),
    (245, 'suicune', 'SUICUNE', 'agua', 0, 0),
    (246, 'larvitar', 'LARVITAR', 'roca', 247, 30),
    (247, 'pupitar', 'PUPITAR', 'roca', 248, 55),
    (248, 'tyranitar', 'TYRANITAR', 'roca', 0, 0),
    (249, 'lugia', 'LUGIA', 'psiquico', 0, 0),
    (250, 'ho-oh', 'HO_OH', 'fuego', 0, 0),
    (251, 'celebi', 'CELEBI', 'psiquico', 0, 0),
    (252, 'treecko', 'TREECKO', 'planta', 253, 16),
    (253, 'grovyle', 'GROVYLE', 'planta', 254, 36),
    (254, 'sceptile', 'SCEPTILE', 'planta', 0, 0),
    (255, 'torchic', 'TORCHIC', 'fuego', 256, 16),
    (256, 'combusken', 'COMBUSKEN', 'fuego', 257, 36),
    (257, 'blaziken', 'BLAZIKEN', 'fuego', 0, 0),
    (258, 'mudkip', 'MUDKIP', 'agua', 259, 16),
    (259, 'marshtomp', 'MARSHTOMP', 'agua', 260, 36),
    (260, 'swampert', 'SWAMPERT', 'agua', 0, 0),
    (261, 'poochyena', 'POOCHYENA', 'siniestro', 262, 18),
    (262, 'mightyena', 'MIGHTYENA', 'siniestro', 0, 0),
    (263, 'zigzagoon', 'ZIGZAGOON', 'normal', 264, 20),
    (264, 'linoone', 'LINOONE', 'normal', 0, 0),
    (265, 'wurmple', 'WURMPLE', 'bicho', 266, 7),
    (266, 'silcoon', 'SILCOON', 'bicho', 267, 10),
    (267, 'beautifly', 'BEAUTIFLY', 'bicho', 0, 0),
    (268, 'cascoon', 'CASCOON', 'bicho', 269, 10),
    (269, 'dustox', 'DUSTOX', 'bicho', 0, 0),
    (270, 'lotad', 'LOTAD', 'agua', 271, 14),
    (271, 'lombre', 'LOMBRE', 'agua', 272, 30),
    (272, 'ludicolo', 'LUDICOLO', 'agua', 0, 0),
    (273, 'seedot', 'SEEDOT', 'planta', 274, 14),
    (274, 'nuzleaf', 'NUZLEAF', 'planta', 275, 30),
    (275, 'shiftry', 'SHIFTRY', 'planta', 0, 0),
    (276, 'taillow', 'TAILLOW', 'normal', 277, 22),
    (277, 'swellow', 'SWELLOW', 'normal', 0, 0),
    (278, 'wingull', 'WINGULL', 'agua', 279, 25),
    (279, 'pelipper', 'PELIPPER', 'agua', 0, 0),
    (280, 'ralts', 'RALTS', 'psiquico', 281, 20),
    (281, 'kirlia', 'KIRLIA', 'psiquico', 282, 30),
    (282, 'gardevoir', 'GARDEVOIR', 'psiquico', 0, 0),
    (283, 'surskit', 'SURSKIT', 'bicho', 284, 22),
    (284, 'masquerain', 'MASQUERAIN', 'bicho', 0, 0),
    (285, 'shroomish', 'SHROOMISH', 'planta', 286, 23),
    (286, 'breloom', 'BRELOOM', 'planta', 0, 0),
    (287, 'slakoth', 'SLAKOTH', 'normal', 288, 18),
    (288, 'vigoroth', 'VIGOROTH', 'normal', 289, 36),
    (289, 'slaking', 'SLAKING', 'normal', 0, 0),
    (290, 'nincada', 'NINCADA', 'bicho', 291, 20),
    (291, 'ninjask', 'NINJASK', 'bicho', 0, 0),
    (292, 'shedinja', 'SHEDINJA', 'bicho', 0, 0),
    (293, 'whismur', 'WHISMUR', 'normal', 294, 20),
    (294, 'loudred', 'LOUDRED', 'normal', 295, 40),
    (295, 'exploud', 'EXPLOUD', 'normal', 0, 0),
    (296, 'makuhita', 'MAKUHITA', 'lucha', 297, 24),
    (297, 'hariyama', 'HARIYAMA', 'lucha', 0, 0),
    (298, 'azurill', 'AZURILL', 'normal', 183, 10),
    (299, 'nosepass', 'NOSEPASS', 'roca', 0, 0),
    (300, 'skitty', 'SKITTY', 'normal', 301, 30),
    (301, 'delcatty', 'DELCATTY', 'normal', 0, 0),
    (302, 'sableye', 'SABLEYE', 'siniestro', 0, 0),
    (303, 'mawile', 'MAWILE', 'acero', 0, 0),
    (304, 'aron', 'ARON', 'acero', 305, 32),
    (305, 'lairon', 'LAIRON', 'acero', 306, 42),
    (306, 'aggron', 'AGGRON', 'acero', 0, 0),
    (307, 'meditite', 'MEDITITE', 'lucha', 308, 37),
    (308, 'medicham', 'MEDICHAM', 'lucha', 0, 0),
    (309, 'electrike', 'ELECTRIKE', 'electrico', 310, 26),
    (310, 'manectric', 'MANECTRIC', 'electrico', 0, 0),
    (311, 'plusle', 'PLUSLE', 'electrico', 0, 0),
    (312, 'minun', 'MINUN', 'electrico', 0, 0),
    (313, 'volbeat', 'VOLBEAT', 'bicho', 0, 0),
    (314, 'illumise', 'ILLUMISE', 'bicho', 0, 0),
    (315, 'roselia', 'ROSELIA', 'planta', 0, 0),
    (316, 'gulpin', 'GULPIN', 'veneno', 317, 26),
    (317, 'swalot', 'SWALOT', 'veneno', 0, 0),
    (318, 'carvanha', 'CARVANHA', 'agua', 319, 30),
    (319, 'sharpedo', 'SHARPEDO', 'agua', 0, 0),
    (320, 'wailmer', 'WAILMER', 'agua', 321, 40),
    (321, 'wailord', 'WAILORD', 'agua', 0, 0),
    (322, 'numel', 'NUMEL', 'fuego', 323, 33),
    (323, 'camerupt', 'CAMERUPT', 'fuego', 0, 0),
    (324, 'torkoal', 'TORKOAL', 'fuego', 0, 0),
    (325, 'spoink', 'SPOINK', 'psiquico', 326, 32),
    (326, 'grumpig', 'GRUMPIG', 'psiquico', 0, 0),
    (327, 'spinda', 'SPINDA', 'normal', 0, 0),
    (328, 'trapinch', 'TRAPINCH', 'tierra', 329, 35),
    (329, 'vibrava', 'VIBRAVA', 'tierra', 330, 45),
    (330, 'flygon', 'FLYGON', 'tierra', 0, 0),
    (331, 'cacnea', 'CACNEA', 'planta', 332, 32),
    (332, 'cacturne', 'CACTURNE', 'planta', 0, 0),
    (333, 'swablu', 'SWABLU', 'normal', 334, 35),
    (334, 'altaria', 'ALTARIA', 'dragon', 0, 0),
    (335, 'zangoose', 'ZANGOOSE', 'normal', 0, 0),
    (336, 'seviper', 'SEVIPER', 'veneno', 0, 0),
    (337, 'lunatone', 'LUNATONE', 'roca', 0, 0),
    (338, 'solrock', 'SOLROCK', 'roca', 0, 0),
    (339, 'barboach', 'BARBOACH', 'agua', 340, 30),
    (340, 'whiscash', 'WHISCASH', 'agua', 0, 0),
    (341, 'corphish', 'CORPHISH', 'agua', 342, 30),
    (342, 'crawdaunt', 'CRAWDAUNT', 'agua', 0, 0),
    (343, 'baltoy', 'BALTOY', 'tierra', 344, 36),
    (344, 'claydol', 'CLAYDOL', 'tierra', 0, 0),
    (345, 'lileep', 'LILEEP', 'roca', 346, 40),
    (346, 'cradily', 'CRADILY', 'roca', 0, 0),
    (347, 'anorith', 'ANORITH', 'roca', 348, 40),
    (348, 'armaldo', 'ARMALDO', 'roca', 0, 0),
    (349, 'feebas', 'FEEBAS', 'agua', 350, 30),
    (350, 'milotic', 'MILOTIC', 'agua', 0, 0),
    (351, 'castform', 'CASTFORM', 'normal', 0, 0),
    (352, 'kecleon', 'KECLEON', 'normal', 0, 0),
    (353, 'shuppet', 'SHUPPET', 'fantasma', 354, 37),
    (354, 'banette', 'BANETTE', 'fantasma', 0, 0),
    (355, 'duskull', 'DUSKULL', 'fantasma', 356, 37),
    (356, 'dusclops', 'DUSCLOPS', 'fantasma', 0, 0),
    (357, 'tropius', 'TROPIUS', 'planta', 0, 0),
    (358, 'chimecho', 'CHIMECHO', 'psiquico', 0, 0),
    (359, 'absol', 'ABSOL', 'siniestro', 0, 0),
    (360, 'wynaut', 'WYNAUT', 'psiquico', 202, 15),
    (361, 'snorunt', 'SNORUNT', 'hielo', 362, 42),
    (362, 'glalie', 'GLALIE', 'hielo', 0, 0),
    (363, 'spheal', 'SPHEAL', 'hielo', 364, 32),
    (364, 'sealeo', 'SEALEO', 'hielo', 365, 44),
    (365, 'walrein', 'WALREIN', 'hielo', 0, 0),
    (366, 'clamperl', 'CLAMPERL', 'agua', 367, 40),
    (367, 'huntail', 'HUNTAIL', 'agua', 0, 0),
    (368, 'gorebyss', 'GOREBYSS', 'agua', 0, 0),
    (369, 'relicanth', 'RELICANTH', 'agua', 0, 0),
    (370, 'luvdisc', 'LUVDISC', 'agua', 0, 0),
    (371, 'bagon', 'BAGON', 'dragon', 372, 30),
    (372, 'shelgon', 'SHELGON', 'dragon', 373, 50),
    (373, 'salamence', 'SALAMENCE', 'dragon', 0, 0),
    (374, 'beldum', 'BELDUM', 'acero', 375, 20),
    (375, 'metang', 'METANG', 'acero', 376, 45),
    (376, 'metagross', 'METAGROSS', 'acero', 0, 0),
    (377, 'regirock', 'REGIROCK', 'roca', 0, 0),
    (378, 'regice', 'REGICE', 'hielo', 0, 0),
    (379, 'registeel', 'REGISTEEL', 'acero', 0, 0),
    (380, 'latias', 'LATIAS', 'dragon', 0, 0),
    (381, 'latios', 'LATIOS', 'dragon', 0, 0),
    (382, 'kyogre', 'KYOGRE', 'agua', 0, 0),
    (383, 'groudon', 'GROUDON', 'tierra', 0, 0),
    (384, 'rayquaza', 'RAYQUAZA', 'dragon', 0, 0),
    (385, 'jirachi', 'JIRACHI', 'acero', 0, 0),
    (386, 'deoxys', 'DEOXYS', 'psiquico', 0, 0),
]

# el primer huevo de la partida siempre es un inicial clasico
CLASSIC = [1, 4, 7, 25, 133]

# rarezas de las formas base (lo que no este aqui y sea base = comun)
RARE = {58, 77, 83, 88, 95, 106, 107, 108, 111, 113, 114, 115, 122, 123,
        124, 125, 126, 127, 128, 131, 132, 137, 138, 140, 142, 143, 147,
        175, 193, 198, 200, 201, 206, 213, 214, 215, 222, 225, 226, 227,
        234, 235, 236, 238, 239, 240, 241, 246,
        302, 303, 324, 327, 335, 336, 337, 338, 345, 347, 349, 352, 357, 359,
        361, 369, 370, 371, 374}
LEGENDARY = {144, 145, 146, 150, 151, 243, 244, 245, 249, 250, 251,
             377, 378, 379, 380, 381, 382, 383, 384, 385, 386}

# Evolutions that use a condition other than the normal level field in DEX.
# The generator emits the primary DEX evolution for every other entry and
# appends these branches. Conditions are interpreted by Pet in the firmware.
EVOLUTION_RULE_OVERRIDES = {
    172: [(25, 10, 'BOND')],       # Pichu -> Pikachu
    173: [(35, 10, 'BOND')],       # Cleffa -> Clefairy
    174: [(39, 10, 'BOND')],       # Igglybuff -> Jigglypuff
    175: [(176, 10, 'BOND')],      # Togepi -> Togetic
    236: [(106, 20, 'ATK_GT_DEF'), (107, 20, 'DEF_GT_ATK'),
          (237, 20, 'ATK_EQ_DEF')],
    271: [(272, 30, 'LEVEL')],
    274: [(275, 30, 'LEVEL')],
    298: [(183, 10, 'BOND')],
    300: [(301, 30, 'LEVEL')],
    349: [(350, 30, 'BOND')],
    366: [(367, 40, 'LEVEL')],
}

# Additional Gen-2 branches and item/trade replacements. The project has no
# item or link-trade inventory, so those triggers use a level equivalent.
EVOLUTION_EXTRA = [
    (42, 169, 30, 'BOND'),        # Golbat -> Crobat
    (44, 182, 36, 'LEVEL'),       # Gloom -> Bellossom
    (61, 186, 36, 'LEVEL'),       # Poliwhirl -> Politoed
    (79, 199, 37, 'LEVEL'),       # Slowpoke -> Slowking
    (95, 208, 30, 'LEVEL'),       # Onix -> Steelix
    (113, 242, 30, 'BOND'),       # Chansey -> Blissey
    (117, 230, 42, 'LEVEL'),       # Seadra -> Kingdra
    (123, 212, 30, 'LEVEL'),       # Scyther -> Scizor
    (133, 135, 30, 'LEVEL'),       # Eevee -> Jolteon
    (133, 136, 30, 'LEVEL'),       # Eevee -> Flareon
    (133, 196, 30, 'DAY_BOND'),    # Eevee -> Espeon
    (133, 197, 30, 'NIGHT_BOND'),  # Eevee -> Umbreon
    (137, 233, 30, 'LEVEL'),       # Porygon -> Porygon2
    (265, 268, 7, 'LEVEL'),
    (290, 292, 20, 'LEVEL'),
    (366, 368, 40, 'LEVEL'),
]

SLUGS = {n: s for n, s, *_ in DEX}
